BIN		:= enet.com
INSTDIR := bin
CONSOLE := BDOS
SRCC	:= main.c
SRCH	:= ../common/esp-com.c ../common/espnet.c ../common/ini.c ../iarlib/espnet.h ../common/espnet/protocol.h
SRCA	:=
XCLFILE	:= lnk.xcl
include ../iarlib/iar.mk
