T_BUTTON=1
T_LABEL=2
T_EDIT=3
T_RADIO=4
T_FLAG=5
T_MENUITEM=6
T_HORBAR=7
T_TITLE=8
        
WINELEMENTSTRUCTSIZE=15
WINDESCRIPTORSIZE=5

       macro STARTWINELEMENT
_=$
       endm

       macro PADWINELEMENT
       ds WINELEMENTSTRUCTSIZE-($-_)
       endm

WINELEMENT_NEXT=0 ;0=end of list
WINELEMENT_X=2
WINELEMENT_Y=3
WINELEMENT_WID=4
WINELEMENT_HGT=5
WINELEMENT_TYPE=6
WINELEMENT_FLAGS=7 ;b0:checked, b1:hidden, b2:disabled, b3:invertible
WINELEMENT_FLAG_CHECKED=0
WINELEMENT_FLAG_HIDDEN=1
WINELEMENT_FLAG_DISABLED=2
WINELEMENT_FLAG_INVERTIBLE=3
WINELEMENT_HOTKEY=8
WINELEMENT_CLICK=9
WINELEMENT_UNCLICK=11
WINELEMENT_MOVE=13
