#название запускаемого файла
BIN		:= zxdb.com

#поддиректория инсталляции в release
INSTDIR := bin

#тип вводавывода TTY или BDOS
CONSOLE := BDOS

#файлы .с
SRCC	:= main.c
#файлы .h
SRCH	:= ../common/espnet.c ../common/espnet-net.c
#файлы .asm
SRCA	:=
#линковочный файл-скрипт. можно не указывать, тогда будет использоватся стандартный
XCLFILE	:= lnk.xcl


include ../../kapps/iarlib/iar.mk
