; ESP UART (espcom.ini)
; comType: 0 Kondratyev w/o AFC 115200
;          1 ATM2 COM 38400
;          2 Kondratyev AFC 115200
;          3 ATM2IOESP w/o AFC 115200
RBR_THR = 0xF8EF
IER = 0xF9EF
IIR_FCR = 0xFAEF
LCR = 0xFBEF
MCR = 0xFCEF
LSR = 0xFDEF
MSR = 0xFEEF
SR = 0xFFEF
divider = 1
comType = 0
espType = 32
espRetry = 40
