
;LAST UPDATE: 02.02.2019 savelij

;автоопределение кодировки работает неправильно

		;RELAXED ON
		;CPU Z80UNDOC

BUILD_DEBUG	EQU 0

;DZ		MACRO DEFZ
;		DB DEFZ,0
;		ENDM 

;DC		MACRO DEFC
;		IF STRLEN(DEFC)>1
;		DB SUBSTR(DEFC,0,STRLEN(DEFC)-1)
;		ENDIF
;		IF STRLEN(DEFC)>0
;		DB CHARFROMSTR(DEFC,STRLEN(DEFC)-1)|80H
;		ENDIF
;		ENDM


;DUPL		MACRO LEN,FILL
;DUPL:
;$$N		EQU (LEN) / 1024
;$$M		EQU (LEN) # 1024
;		REPT $$N
;		DB 1024 DUP(FILL)
;		ENDM
;		IF $$M <> 0
;		IFB FILL
;		DB $$M DUP(0)
;		ELSE
;		DB $$M DUP(FILL)
;		ENDIF
;		ENDIF
;		ENDM

;HIGH		FUNCTION X,((X >> 8) & 0XFF)
;LOW		FUNCTION X,(X & 0XFF)

		MACRO PCALL ADR,PAGE
		RST 0X30
		DW ADR
		DB PAGE
		ENDM

		MACRO ATMPORT PORT,BYTE
		LD BC,PORT
		LD A,BYTE
		OUT (C),A
		ENDM

		MACRO EVOPORT PORT,BYTE
		LD BC,PORT
		LD A,BYTE
		OUT (C),A
		ENDM

;PEC_ON		MACRO BYTE
;		IN A,(PEVO_CONF)
;		OR BYTE
;		OUT (PEVO_CONF),A
;		ENDM

;PEC_OFF		MACRO BYTE
;		IN A,(PEVO_CONF)
;		AND BYTE!0XFF
;		OUT (PEVO_CONF),A
;		ENDM

;READ_7FFD	MACRO
;		LD A,HIGH (RD_7FFD)
;		IN A,(LOW (RD_7FFD))
;		ENDM

;SIZEDATE	EQU STRLEN (DATE)
;SIZETIME	EQU STRLEN (TIME)


;DATA_VERS	EQU DDATE+(MMOUNTH<<5)+(YYEAR<<9)+0X8000			;уже упаковано

;FAT_DATE	EQU DDATE+(MMOUNTH<<5)+((2000+YYEAR-1980)&0x7F)<<9
;FAT_TIME	EQU SSECUND/2+(MMINUTE<<5)+(HHOUR<<11)

;BYTE		EQU 1
;WORD		EQU 2
;JUMP		EQU 3
;DWORD		EQU 4
;QWORD		EQU 8

;	MACRO INIT_VAR
;_=0
;	ENDM

	;MACRO SETVAR 
	;ENDM
	