;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		Ｈシーン　星愛３
;		
	INCLUDE	SUPER_S.INC

START:
	DW	SCTBL,MSGTBL,COMTBL,VNTBL,ENDTBL
SCTBL:
	DW	S1
MSGTBL:
	DW	M1
COMTBL:
	DW	CM1
VNTBL:
	DW	V_FNAME,N_FNAME
ENDTBL:
	INCLUDE	"V_NAME00.INC"			; 0=NoCommand , 1-49=NormalCommand
	INCLUDE	"N_NAME00.INC"			; 50-99=HseenCommand

;	　　　 動詞　　名詞群
CM1:

;	　　　 動詞 名詞 ﾌﾗｸﾞ ﾒｯｾｰｼﾞ
S1:

;イニシャルメッセージ
M1:
	DB	BGM,13
;	DB	'【星愛】：・・・ひぃっ！！'
	DB	"Seia:  .....Ahhhn!"
	E_CG B_FADE,'AE_164'
	DB	NEXT
;	DB	'一瞬、何かに突き当たる感覚。'
	DB	"A massive wave of pleasure washed over me."
	DB	NEXT
;	DB	'だが俺の物は何事も無かったかのようにそれを突き抜け、'
;	DB	'柔らかい何かに突き当たって止まった。'
	DB	"But something inside her resisted my cock's full"
	DB	CR
	DB	"penetration, like a warm, wet barrier."
	DB	NEXT
;	DB	'【星愛】：・・・う・・・あ・・・'
	DB	"Seia:  .....Uuuu.....ahh...."
	DB	NEXT
;	DB	'そのまま、腰を引き・・・突き入れる。'
	DB	"Slowly, I pushed inside, breaking her."
	DB	NEXT
;	DB	'【星愛】：・・・うぁあっ！'
	DB	"Seia:  ......Uwaaa!!"
	DB	NEXT
;	DB	'ぬるぬるした何かが、俺の物を刺激する。'
	DB	"Her wet walls were all around me, stimulating me."
	DB	NEXT
;	DB	'俺はその刺激に突き動かされ、何度も何度も腰を突き出し、引く。'
	DB	"I continued thrusting into her, opening her more and more."
	DB	NEXT
;	DB	'【星愛】：・・・うっ・・・うぅっ・・・'
	DB	"Seia:  .....Uuuu......No!"
	DB	NEXT
;	DB	'【星愛】：・・・・あっ・・・はぐっ・・・'
	DB	"Seia:  ...........Uuuuuu.......Ahhh........"
	DB	NEXT
;	DB	'【星愛】：・・・くぁっ・・・ひぐぅっ・・・'
	DB	"Seia:  .............Ahhhhnnn......."
	DB	NEXT
;	DB	'・・・そして、身体の奥底から沸き上がる、痺れるようなあの感覚。'
	DB	"Suddenly a warm feeling started building in my legs."
	DB	NEXT
;	DB	'それはぼんやりと腰の辺りに広がり・・・'
	DB	"The sensation spread to my whole body."
	DB	PAUSE
;	DB	'淒まじい勢いで一点に集中し、噴き出した。'
	DB	" Everything was focused"
	DB	CR
	DB	"on that feeling. Then I let go."
	DB	NEXT
;	DB	'どくどくどく・・・'
	DB	"......My hot flow rushed into her."
	DB	NEXT
;	DB	'【星愛】：・・・あ！'
	DB	"Seia:  .......Ahh!"
	DB	PAUSE
	B_O B_FADE
;	DB	'・・・あああああ・・・'
	DB	"....Ahhhhhhhhh....."
	DB	NEXT
;	DB	'・・・・・・・・・・・・・・・・'
	DB	"......................................"
	DB	NEXT
;	DB	'【%001】：・・・吉田・・・その・・・'
;	DB	"%001:  Seia, I'm..."
;	DB	NEXT
;	DB	'【星愛】：・・・・・・・・・'
	DB	"Seia:  ................................"
	DB	NEXT
;	DB	'あの後－－－－－－－－－'
	DB	"Afterwards...."
	DB	NEXT
;	DB	'自分の仕出かした事に気が付いた俺は、後悔の余りどうしていいか判らず'
;	DB	'吉田が身仕度を整えるのをただ茫然と見ていた。'
	DB	"Realizing the terrible thing I'd done to Seia, I could"
	DB	CR
	DB	"find nothing to do for her than re-arrange her clothes."
	DB	NEXT
;	DB	'吉田はさっきから俺に背を向け、一言も口をきいてくれない。'
	DB	"Seia did nothing but turn her back to me wordlessly."
	DB	NEXT
;	DB	'（・・・あったりまえか・・・）'
	DB	"......I couldn't blame her for hating me."
	DB	NEXT
;	DB	'【%001】：・・・吉田・・・俺・・・'
	DB	"%001:  ........Seia, I..."
	DB	NEXT
;	DB	'【星愛】：・・・ひどいですわ・・・わたくし、初めてでしたのに・・・'
	DB	"Seia:  .....I can't.... I can't believe you did that..."
	DB	CR
	DB	"It was my first time!"
	DB	NEXT
;	DB	'吉田の言葉が、俺の胸を鋭く抉り取る。'
	DB	"Seia's harsh words stabbed me through the heart."
	DB	NEXT
;	DB	'俺は言葉どころか、息すら詰まる思いがした。'
	DB	"I couldn't utter a word. I was totally speechless."
	DB	NEXT
;	DB	'【%001】：・・・吉田・・・何を言っても言い訳になるかもしれないけど・・・'
	DB	"%001:  ......Seia, I'm sure there's nothing I can say that"
	DB	CR
	DB	"will matter to you now, but..."
	DB	NEXT
;	DB	'【星愛】：・・・・・・次は、もっと優しくして下さいね。'
	DB	"Seia:  ....Next time, I want you to be more gentle..."
	DB	NEXT
;	DB	'【%001】：・・・・・・・・・'
	DB	"%001:  ................................"
	DB	PAUSE
;	DB	'え？'
	DB	"What?"
	DB	NEXT
;	DB	'【星愛】：・・・それとも、遊びだったのですか？'
	DB	"Seia:  ...........Or were you just playing with me?"
	DB	NEXT
;	DB	'俺は。'
	DB	"%001:  ......................"
	DB	NEXT
;	DB	'俺は吉田の・・・・・・星愛の小柄な体を後ろから抱きしめた。'
	DB	"I embraced Seia from behind."
	DB	NEXT
;	DB	'【星愛】：・・・あん、%001君・・・痛いですわ。'
	DB	"Seia:  .....Ahn, %001... That hurts!"
	DB	NEXT
;	DB	'【%001】：・・・・・・星愛・・・・・・！'
	DB	"%001:  ............Seia!"
	DB	NEXT
;	DB	'【星愛】：・・・%001・・・'
	DB	"Seia:  ..............%001....."
	DB	NEXT
;	DB	'俺達は・・・・・・肩越しに、もう一度口付けを交わした。'
	DB	"We kissed again, then, over her shoulder."
	DB	NEXT
;	DB	'熱く甘い・・・・・・本当のキスを。'
	DB	"Hot, sweet... A real kiss."
	DB	NEXT
	DB	BGM,33
	DB	ENDING,7
	DW	0000H


end
