	INCLUDE	SUPER_S.INC

;	DB	'今年も、桜が咲いた。'
	DB	"It's spring. The sakura are in bloom again."
	DW	0000H
;	DB	'「俺達が出会った時も、こんな風に桜が咲いていたよな。」'
	DB	"I turn to you, standing beside me, and speak."
	DB	CR
;	DB	'俺は、傍らにいる彼女に語りかける。'
	DB	"'The sakura were in bloom the day we first met, weren't they...'"
	DW	0000H
;	DB	'彼女は、ただ微笑むだけだ。幸せそうに。'
	DB	"She smiles at me. I know that she is happy."
	DW	0000H
;	DB	'俺はもう一度桜を見上げると、独り言のように続けた。'
	DB	"I look up at the sakura once more, and remember..."
	DW	0000H
;	DB	'「そうだよ・・・あの時に、全てが始まったんだ・・・・・・」'
	DB	"That's right. That's when all of this began..."
	DW	0000H


end