;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		美緒のエンディングテキスト
;		

	INCLUDE	SUPER_S.INC

;	DB	'新学期が始まったのと同時に、俺はテニス部に入部した。'
	DB	"In April, I joined the tennis team."
	DB	NEXT
;	DB	'【%001】：美緒。俺とお前と、どっちが先に高校日本一になるか、勝負だな！'
	DB	"%001:  I wonder which one of will win the Japan Tennis"
	DB	CR
	DB	"Championships first."
	DB	NEXT
;	DB	'【美緒】：アタシ、負けないよ！'
	DB	"Mio:  I won't lose!"
	DB	NEXT
;	DB	'【美緒】：・・・・・・・・・・・・あれ？'
	DB	"Mio:  .....Huh?"
	DB	NEXT
;	DB	'【%001】：ん？どした？'
	DB	"%001:  What's wrong?"
	DB	NEXT
;	DB	'【美緒】：うん・・・。こういう話をしてると、必ず現れるはずなんだけど・・・'
	DB	"Mio:  Every time I get my competitive spirit up like that,"
	DB	CR
	DB	"she shows up. I wonder where she is."
	DB	NEXT
;	DB	'【%001】：ああ、亜希ちゃんならサバ研の新勧を手伝ってた。'
	DB	"%001:  If you're talking about Aki, she joined the Survival"
	DB	CR
	DB	"Club."
	DB	NEXT
;	DB	'【美緒】：誠先輩の？'
	DB	"%001:  With Makoto?"
	DB	NEXT
;	DB	'【%001】：誠のヤツ・・・さんざん俺に、',CR,'「年下が好きだなんて、お前ロリコンか？」',CR,'とか言ってたくせに・・・'
	DB	"%001:  Yes. I wouldn't have believed it either, if I hadn't"
	DB	CR
	DB	"seen it for myself."
	DB	NEXT
;	DB	'・・・・・・・・・・・・・・・・・・・・・'
	DB	".................................."
	DB	NEXT
;	DB	'【美緒】：先輩・・・今年も桜が満開だね！'
	DB	"Mio:  Look, %001. The sakura are in bloom!"
	DB	NEXT
;	DB	'【%001】：・・・'
	DB	"%001:  ........................"
	DB	NEXT
;	DB	'【美緒】：先輩？'
	DB	"Mio:  %001?"
	DB	NEXT
;	DB	'【%001】：あ、ああ・・・あんまり桜が綺麗なんで、見愡れちまった・・・。'
	DB	"%001:  Oh, I was just thinking how pretty the sakura were..."
	DB	NEXT
;	DB	'俺が見愡れてたのは美緒だ。美緒はそれを知ってか知らずか、俺に最高の笑顔を見せてくれる。'
	DB	"That was a lie. I was looking at Mio, with the sakura behind"
	DB	CR
	DB	"her."
	DB	NEXT
	DB	"Whether or not she knew this, she smiled."
	DB	NEXT
;	DB	'【%001】：・・・・・・その・・・笑わないで聞いてくれよ？'
	DB	"%001:  ....Want to hear something funny?"
	DB	NEXT
;	DB	'【美緒】：なに・・・？'
	DB	"Mio:  What?"
	DB	NEXT
;	DB	'【%001】：初めて美緒に会った時さ・・・'
	DB	"%001:  The first time I met you... I thought you were some"
	DB	CR
	DB	"sort of sakura sprite."
	DB	NEXT
;	DB	'（そう・・・あの時に、全てが始まったんだ・・・！）'
	DB	CR,".....That's right... That was the start of it all!"
	DW	0000H


end
