;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		鈴子エンディング
;		
	INCLUDE	SUPER_S.INC

;	DB	'俺の隣には、彼女がいる。'
	DB	"Reiko is standing next to me."
	DB	NEXT
;	DB	'【%001】：・・・'
	DB	"%001:  ......................."
	DB	NEXT
;	DB	'【鈴子】：どうしたのよ、仏頂面しちゃって。'
	DB	"Reiko:  What's wrong? Why are you frowning like that?"
	DB	NEXT
;	DB	'【%001】：・・・地元の大学に進学するなんて、聞いてなかったぜ俺。'
	DB	"%001:  .......I still can't believe you did that!"
	DB	NEXT
;	DB	'【鈴子】：もう、まだすねてるの？'
	DB	"Reiko:  Are you still going on about that?"
	DB	NEXT
;	DB	'そーなのだ。鈴子さんは本鮪大学の推薦入学を辞退して、地元の梶木大学に進学するのである。'
	DB	"Reiko had cancelled her application to Honmaguro"
	DB	CR
	DB	"University, and applied to a local college instead."
	DB	NEXT
;	DB	'【%001】：それならそ～と先に言ってくれれば・・・'
	DB	"%001:  And why didn't you ask me how I felt, first?"
	DB	NEXT
;	DB	'【鈴子】：いいじゃない、減るもんじゃなし。'
	DB	"Reiko:  It doesn't matter. At least we'll be able to see"
	DB	CR
	DB	"each other now."
	DB	NEXT
;	DB	'【%001】：・・・減るんだい。'
	DB	"%001:  I know, but...."
	DB	NEXT
;	DB	'【鈴子】：私は金メダルの夢も%001君も、両方大事だもの。'
	DB	"Reiko:  I just couldn't leave, not now. Both you and that"
	DB	CR
	DB	"gold medal are important to me."
	DB	NEXT
;	DB	'%001君は、私が遠くに行った方がよかったの？'
	DB	"%001, would you rather have me go far away, instead?"
	DB	NEXT
;	DB	'【%001】：そんなことないよ！'
	DB	"%001:  Of course not!"
	DB	NEXT
;	DB	'【鈴子】：なら、いいじゃない。'
	DB	"Reiko:  Then it's settled."
	DB	NEXT
;	DB	'【鈴子】：どこに行こうと、私は私。行く大学で左右されるような安い才能は持ち合せてないわ。'
	DB	"Reiko:  No matter what college I go to, I'm me. If I'm"
	DB	CR
	DB	"good enough for the olympics, it doesn't matter what"
	DB	CR
	DB	"school I go to."
	DB	NEXT
;	DB	'【鈴子】：それに、確かに本鮪大学は設備が整ってるけど、%001君がそばにいてくれる方が練習に身が入るもの。'
	DB	"Reiko:  Honmaguro has exceptional training facilities,"
	DB	CR
	DB	"but having you near me will help me more."
	DB	NEXT
;	DB	'【鈴子】：二人で追いかけましょう、私たちの夢を・・・ね？'
	DB	"Reiko:  Let's go to the olympics together, alright?"
	DB	NEXT
;	DB	'【%001】：・・・・・・'
	DB	"%001:  ...................."
	DB	NEXT
;	DB	'鈴子さんの笑顔の前には、俺の仏頂面なんてひとたまりもなかった。'
	DB	"Reiko smiles, and my frown melts away."
	DB	NEXT
;	DB	'【鈴子】：%001君・・・大好きよ。'
	DB	"Reiko:  I love you, %001."
	DB	NEXT
;	DB	'・・・ま、いっか。'
	DB	"......Well, what the hell?"
	DB	NEXT
;	DB	'【%001】：・・・俺もだよ、鈴子さん・・・！'
	DB	"%001:  Me too, Reiko...!"
	DW	0000H


end
