;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		エンディング（恵依美）
;		
	INCLUDE	SUPER_S.INC
;	DB	'
;	DB	'・・・そして、３年後・・・'
	DB	"Three years passed..."
	DB	NEXT
;	DB	'俺と恵依美は、恵依美の母親がかつていたサーカス団で活躍していた。'
	DB	"Meimi and I joined the circus group that Meimi's mother"
	DB	CR
	DB	"belonged to."
	DB	NEXT
;	DB	'・・・と言ってもまぁ、主に活躍しているのは恵依美で・・・俺はにぎやかしだ。'
	DB	"Meimi was the star, of course. I just helped out where I"
	DB	CR
	DB	"could."
	DB	NEXT
;	DB	'一応俺も、苦心惨澹した甲斐あってピエロをやらせてもらえるまでにはなった。'
	DB	"They're letting me fill in for one of the clowns this"
	DB	CR
	DB	"season."
	DB	NEXT
;	DB	'・・・だけど、観客の歓声とスポットライトは恵依美の物だ。',CR
;	DB	'それでいい、と俺は思っている。'
	DB	"....The applause and the spotlight are all for Meimi. That's"
	DB	CR
	DB	"fine with me."
	DB	NEXT
;	DB	'俺はあの日に決めたんだ。恵依美をずっと、応援し続けると。'
	DB	"Ever since that day, I'd made up my mind to be there for "
	DB	CR
	DB	"her no matter what she did."
	DB	NEXT
;	DB	'俺には観客の歓声より、恵依美のあの笑顔が必要なんだ。'
	DB	"More than the cheers of the audience, I need Meimi's smile."
	DB	NEXT
;	DB	'そして恵依美は、俺が望めばいつでもそれを見せてくれる。'
	DB	"Meimi shows it to me whenever I ask for it."
	DB	NEXT
;	DB	'他に、何が要ると言うのだろう？'
	DB	"What else do I need out of life?"
	DB	NEXT
;	DB	'・・・・・・今日も天幕の中に、紙ふぶきが舞う。'
	DB	"......From the roof, pink confetti is released, falling"
	DB	CR
	DB	"down into the ring. It makes me think of sakura petals."
	DB	NEXT
;	DB	'紙ふぶきがさくらの花びらに見える時、俺はいつも思い出す。',CR
;	DB	'恵依美と過ごした、あの日々を。'
	DB	"I remember...the season of the sakura."
	DB	NEXT
	DB	CR
;	DB	'（・・・そうだよ・・・あの時に、全てが始まったんだ・・・！）'
	DB	"(That's right! That was the start of it all...!)"
	DW	0000H


end
