;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		エンディング（星愛）
;		

	INCLUDE	SUPER_S.INC


;イニシャルメッセージ
M1:
;	DB	'・・・そして今年も、さくらが咲いた。'
	DB	"It's April. The sakura are in bloom again."
	DB	NEXT
;	DB	'俺はわらわらとやって来る新入生達をぼんやり眺めながら、今までの事を思い出していた。'
	DB	"I was watching the new freshmen coming to school for the"
	DB	CR
	DB	"first day, and remembering everything that had taken"
	DB	CR
	DB	"place..."
	DB	NEXT
;	DB	'・・・・・・そして・・・・・・'
	DB	"Then....."
	DB	NEXT
;	DB	'【星愛】：・・・どうかしまして？%001。'
	DB	"Seia:  What's wrong, %001?"
	DB	NEXT
;	DB	'【%001】：・・・・・・いや、ちょっとね・・・・・・'
	DB	"Next to me was Seia, standing with the sakura falling all"
	DB	CR
	DB	"around her."
	DB	NEXT
	DB	"%001:  Mm? Oh, I was just thinking...."
	DB	NEXT
;	DB	'そして俺の隣には、彼女がいる。'
;	DB	'「イギリスに行こうか？」'
	DB	"%001:  Let's go to England."
	DB	NEXT
;	DB	'こう切り出した時の星愛の顔は、中々見物だった。'
	DB	"As I said it, the corners of her mouth turned upwards."
	DB	NEXT
;	DB	'「・・・高校卒業して就職したら、金貯めて行こうぜ。お前のシスターの元に。・・・俺も、１度くらいは会っておきたいからな。'
;	DB	'お前だって、会いたいだろ？」'
	DB	"%001:  After we graduate and save up some money, let's"
	DB	CR
	DB	"go. I'd like to meet this sister who had such an effect"
	DB	CR
	DB	"on you. You want to go, don't you?"
	DB	NEXT
;	DB	'・・・・・・そう、今の俺には目標がある。'
	DB	"......Yes, I had something to strive for now."
	DB	NEXT
;	DB	'たどり着く道程は未だ全然考えてないけれど、それは２人で考えて行こうと思う。'
	DB	"We both do, together."
	DB	NEXT
;	DB	'【星愛】：・・・%001。'
	DB	"Seia:  %001."
	DB	NEXT
;	DB	'【%001】：・・・・・・ん？'
	DB	"%001:  Mm?"
	DB	NEXT
;	DB	'【星愛】：・・・・・・なんでもありませんわ。'
	DB	"Seia:  Nevermind, it's nothing."
	DB	NEXT
;	DB	'言って、笑みをこぼす星愛。'
	DB	"Seia smiled at me."
	DB	NEXT
;	DB	'俺にだけ・・・そう、神様にだって見せない俺だけの、最高の笑顔。'
	DB	"It was a smile she saved only for me...one she didn't even"
	DB	CR
	DB	"show to God."
	DB	NEXT
;	DB	'俺は何だか気恥ずかしくなってさくらを見上げた。'
	DB	"I smiled back, then looked up at the sakura behind her."
	DB	NEXT
;	DB	'今が満開のさくらの隙間から、暖かな日差しがこぼれて来る。'
	DB	"They were in full bloom now. The days would get warmer"
	DB	CR
	DB	"and warmer now."
	DB	NEXT
;	DB	'俺は目を細めながら、独り言のように呟いた。'
	DB	"I reflected on everything that had taken place before"
	DB	CR
	DB	"today, then said, half to myself..."
	DB	NEXT
;	DB	'【%001】：そうだよ・・・あの時に、全てがはじまったんだ・・・！'
	DB	"%001:  That's right! That was the beginning of it all...!"
	DW	0000H


end
