;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		エンディング（亜希）
;		

	INCLUDE	SUPER_S.INC

;	DB	'・・・そして今年も、さくらが咲いた。'
	DB	".....The sakura were in bloom again this spring."
	DB	NEXT
;	DB	'俺はわらわらとやって来る新入生達をぼんやり眺めながら、今までの事を思い出していた。'
	DB	"I watched the new freshmen making their way into the"
	DB	CR
	DB	"school on the first day."
	DB	NEXT
;	DB	'・・・・・・そして・・・・・・'
	DB	"Then....."
	DB	NEXT
;	DB	'【亜希】：・・・せ～んぱい！'
	DB	"Aki:  Hi, there, %001!"
	DB	NEXT
;	DB	'俺の横には、彼女がいる。'
	DB	"I look beside me. Aki was there."
	DB	NEXT
;	DB	'【亜希】：・・・・・・ねえ、先輩・・・・・・'
	DB	"Aki:  ...%001?"
	DB	NEXT
;	DB	'【%001】：ん？'
	DB	"%001:  Mm?"
	DB	NEXT
;	DB	'【亜希】：子供の名前、何にしよっか？'
	DB	"Aki:  What do you want to name our child?"
	DB	NEXT
;	DB	'【%001】：・・・・・・・・・・・・・・・・'
	DB	"%001:  ..............."
	DB	NEXT
;	DB	'【%001】：ゑ゛？'
	DB	"%001:  WHAT?!?!"
	DB	NEXT
;	DB	'【亜希】：・・・・・・な～んてね！'
	DB	"Aki:  ........"
	DB	PAUSE
;	DB	'う・そ☆'
	DB	"Just kidding!"
	DB	NEXT
;	DB	'【%001】：・・・・・・をィをィ・・・・・・'
	DB	"%001:  ....Don't ever do that again!"
	DB	NEXT
;	DB	'【亜希】：・・・でも、あたし%001先輩の子供だったら欲しいな・・・'
	DB	"Aki:  But someday, I want to have your baby."
	DB	NEXT
;	DB	'【%001】：・・・・・・・・・'
	DB	"%001:  ....................."
	DB	NEXT
;	DB	'【%001】：この場合、どーゆー反応をすればいいんだ？'
	DB	"%001:  What's a guy supposed to say in response to"
	DB	CR
	DB	"something like that?"
	DB	NEXT
;	DB	'【亜希】：教えて上げましょうか？'
	DB	"Aki:  Shall I tell you?"
	DB	NEXT
;	DB	'【%001】：え？'
	DB	"%001:  What?"
	DB	NEXT
;	DB	'【亜希】：こーゆー時はね・・・こうするの！'
	DB	"Aki:  This is what you're supposed to do!"
	DB	NEXT
;	DB	'言うなり、俺に飛びつく亜希ちゃん。'
	DB	"Just as she spoke, she jumped at me with her arms open."
	DB	NEXT
;	DB	'心底幸せそうな笑みを、満面に浮かべて。'
	DB	"She smiled. It was a full, happy smile."
	DB	NEXT
;	DB	'今の・・・この亜希ちゃんの笑顔が見られるんなら、それでもいいような気もする。'
	DB	"If I can see that smile every day for the rest of my"
	DB	CR
	DB	"life, I won't have any complaints at all."
	DB	NEXT
;	DB	'俺は亜希ちゃんを抱き寄せると、２人でさくらを見上げた。'
	DB	"I pulled Aki to me, and we both looked up at the"
	DB	CR
	DB	"sakura."
	DB	NEXT
	DB	CR
;	DB	'（・・・そうだよ・・・あの時に、全てが始まったんだ・・・！）'
	DB	"(That's right! That was the beginning of it all...!)"
	DW	0000H


end
