;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		エンディング（祥子）
;		

	INCLUDE	SUPER_S.INC

;	DB	'・・・そして、３年の月日が流れ。'
	DB	"Three years passed."
	DB	NEXT
;	DB	'【祥子】：しゅ・う・くん！'
	DB	"Shoko:  Shu-kun!"
	DB	NEXT
;	DB	'しゅ・う・くん！'
	DB	"Shu-kun....."
	DB	NEXT
;	DB	'【アナウンサー】：・・・ごぉーーーーーーーーーる！'
	DB	"Announcer:  And it's another goal!"
	DB	NEXT
;	DB	'【アナウンサー】：すごい！今期１２回目のハットトリック達成！'
	DB	"Announcer:  This young man is terrific! That's his"
	DB	CR
	DB	"twelfth hat trick this season!"
	DB	NEXT
;	DB	'もぉの凄い新人が現われました！何と若干１９才！恐るべき新人です！'
;	DB	'山神　%001！！'
	DB	"Anouncer:  And his name is.....%001 Yamagami!"
	DB	NEXT
;	DB	'・・・・・・俺はＪリーグにスカウトされ、今年の新人王間違いなし！',CR
;	DB	'と言われている。'
	DB	"......I was scouted by J-League, the Japanese soccer league."
	DB	CR
	DB	"They say I'm a shoe-in for the Rookie of the Year."
	DB	NEXT
;	DB	'そもそも、俺が負けるはずが無い。'
	DB	"I don't know about that..."
	DB	NEXT
;	DB	'・・・ステキな専属サポーターがいる限り。'
	DB	"If I did win, it would all be because of my private"
	DB	CR
	DB	"supporter."
	DB	NEXT
;	DB	'【祥子】：しゅーくーん！がんばれぇー！'
	DB	"Shoko:  Shu-kun! You're great!"
	DB	NEXT
;	DB	'俺は祥子に一つ手を振ると、再びゴール目指して爆走する。'
	DB	"I waved to the cameras. She would know I was really"
	DB	CR
	DB	"waving to her."
	DB	NEXT
;	DB	'さくら舞う季節の、フィールドの中を・・・・・・！'
	DB	"Then I was off down the field again... Running amid the"
	DB	CR
	DB	"falling sakura...!"
	DW	0000H


end
