;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;		清美エンディング
;		
	INCLUDE	SUPER_S.INC

;	DB	'野球部に入った俺は、清美の助けもあって、'
	DB	"I joined the baseball team, and was made a regular in the"
	DB	CR
	DB	"first week. I played first base."
	DB	NEXT
;	DB	'夏の高校野球、俺たち葉桜高校は破竹の勢いで進軍した。'
	DB	"We beat our rival school, and went to the Japan Baseball"
	DB	CR
	DB	"Championships at Koshien Stadium, Osaka."
	DB	NEXT
;	DB	'俺達の血と汗と涙、',CR,'それにマネージャー兼監督代行の指導力の賜物だ。'
	DB	"We owed our victory to our own blood and sweat, and to"
	DB	CR
	DB	"the efforts of our manager, Kiyomi."
	DB	NEXT
;	DB	'【清美】：いよいよ甲子園ですわね。ここまではわたくしの計画通りですわ。'
	DB	"Kiyomi:  Well, we're finally at the Koshien. Everything"
	DB	CR
	DB	"has proceeded according to my plan."
	DB	NEXT
;	DB	'【清美】：緒戦の金輪高校は鉄壁の守備を誇る強敵です。',CR,'今までのように守備の穴を狙うことは出来ませんわ。'
	DB	"Kiyomi:  Our strongest opponent is Kanawa Junior College."
	DB	CR
	DB	"Our tactic of looking for holes in their defense won't"
	DB	CR
	DB	"be enough."
	DB	NEXT
;	DB	'【%001】：な～に、ホームランにしちまえば守備も',CR,'へったくれもねーって。'
	DB	"%001:  Don't forget the home run I'm going to hit for"
	DB	CR
	DB	"you, Kiyomi. That should help some."
	DB	NEXT
;	DB	'【清美】：わたくしが金輪高校の監督なら、',CR,'%001さんは全打席敬遠致しますわね。'
	DB	"Kiyomi:  If I were the coach for the other team, I'd walk"
	DB	CR
	DB	"you. We have to think of that as a possibility."
	DB	NEXT
;	DB	'【%001】：その点はだいじょーぶ。',CR,'あちらさんも観客を敵に回す度胸はねーだろ。'
	DB	"%001:  We don't have to worry about that. The crowd would"
	DB	CR
	DB	"go crazy. The coach wouldn't want to risk turning them"
	DB	CR
	DB	"against him like that."
	DB	NEXT
;	DB	'【清美】：そう・・・勝つのは、わたくしたちですわ。'
	DB	"Kiyomi:  ......We're going to win, aren't we?"
	DB	NEXT
;	DB	'【%001】：よォし、行くぜみんな！'
	DB	"%001:  Yes! We are!"
	DB	NEXT
	DB	"........................................"
	DB	NEXT
;	DB	'「１番、ファースト山神、背番号９９」'
	DB	"First baseman Yamagami, number 99!"
	DB	NEXT
;	DB	'桜の花は散り・・・俺達の夏が今、始まる。'
	DB	"I look, and think I see sakura petals falling. But our"
	DB	CR
	DB	"summer was just beginning."
	DW	0000H


end
