;	さくらの季節	FILENAME:CSas#_##(CS+章+ｼﾅﾘｵ No.(+ｻﾌﾞﾅﾝﾊﾞｰ))
;	DB	';		瑠璃　エンディング
;		
	INCLUDE	SUPER_S.INC

;	DB	'舞い散る桜の中に佇んでいたのは、まぎれもなく白水さんだった。'
	DB	"Standing beside me, sakura petals falling all around"
	DB	CR
	DB	"her, was Ruri."
	DB	NEXT
;	DB	'【%001】：し・・・白水さん！？'
	DB	"%001:  Ruri!"
	DB	NEXT
;	DB	'俺は思わず目をゴシゴシこすった。'
	DB	"I rubbed by eyes, to see if I was dreaming."
	DB	NEXT
;	DB	'【瑠璃】：クス・・・どうしたの？'
	DB	"She smiled at me."
	DB	NEXT
	DB	"Ruri:  ....Why are you so surprised?"
	DB	NEXT
;	DB	'【%001】：それはこっちの台詞だよ！どうして・・・'
	DB	"%001:  Why am I...? How can you ask that? Why are you"
	DB	CR
	DB	"back...?"
	DB	NEXT
;	DB	'【瑠璃】：お母様を説得したの。'
	DB	"Ruri:  I finally got Mother to change her mind."
	DB	NEXT
;	DB	'【%001】：へぇっ？'
	DB	"%001:  About what?"
	DB	NEXT
;	DB	'【瑠璃】：%001君との交際も認めてくれたから。'
	DB	"Ruri:  About us! She's allowing us to see each other."
	DB	NEXT
;	DB	'【%001】：・・・'
	DB	"%001: ....................."
	DB	NEXT
;	DB	'【瑠璃】：また%001君と同じクラスよ。今度は、卒業まで一緒にいられるわ。'
	DB	"Ruri:  I'm in the same class with you again. We'll be"
	DB	CR
	DB	"together until graduation."
	DB	NEXT
;	DB	'【%001】：・・・'
	DB	"%001:  .............................."
	DB	NEXT
;	DB	'【瑠璃】：%001君・・・喜んでくれないの？'
	DB	"Ruri:  %001? Aren't you happy?"
	DB	NEXT
;	DB	'【%001】：瑠璃・・・また会えるなんて、夢みたいだ・・・'
	DB	"%001:  Ruri, I never thought I'd see you again... I"
	DB	CR
	DB	"can't believe you're really here!"
	DB	NEXT
;	DB	'【瑠璃】：ちゃんと、手紙を置いていったのに・・・？'
	DB	"Ruri:  Didn't you read my letter?."
	DB	NEXT
;	DB	'【%001】：・・・・・・・・・'
	DB	"%001:  .................................."
	DB	NEXT
;	DB	'【%001】：・・・ひょっとして・・・',CR,'あの、「いつかまた会える」ってやつ？'
	DB	"%001:  Do you mean the part about 'I'm sure we'll meet"
	DB	CR
	DB	"again, someday'?"
	DB	NEXT
;	DB	'【瑠璃】：・・・私の手紙、変だった・・・？'
	DB	"Ruri:  I guess it wasn't very clear..."
	DB	NEXT
;	DB	'【%001】：・・・・・・・・・'
	DB	"%001:  ......................."
	DB	NEXT
;	DB	'【瑠璃】：・・・ごめんなさい、手紙って書いたことなくて。'
	DB	"Ruri:  I'm sorry. I've never written a letter like that"
	DB	CR
	DB	"before..."
	DB	NEXT
;	DB	'【%001】：・・・そーだったのか・・・はは・・・ハハハ。'
	DB	"%001:  ......Oh, Ruri...!"
	DB	NEXT
;	DB	'俺は力一杯瑠璃を抱きしめた。'
	DB	"I embraced her with all my strength."
	DB	NEXT
;	DB	'去年、桜の散る頃に俺は彼女と出会い・・・、',CR,'今年、桜の花と共に彼女は帰って来た。'
	DB	"I met her last year, just as the sakura blew away...and"
	DB	CR
	DB	"now she had returned to me, with the sakura in full"
	DB	CR
	DB	"bloom."
	DB	NEXT
;	DB	'【%001】：瑠璃、二度と俺から離れるなよ。'
	DB	"%001:  Ruri, don't ever leave me again!"
	DB	NEXT
;	DB	'【瑠璃】：うん・・・ずぅっと一緒よ・・・%001君。'
	DB	"Ruri:  I won't. We'll be together forever, %001."
	DW	0000H


end
