        MACRO DCOM wrd
        DB wrd&0xff;\0
        ORG $+255        DB wrd/256;'(\0)        ORG $-256        ENDM
;--------------------- -----------------------
MAINCOMS
;#0X
        DCOM RTI_JMP_RTS_SWAB ;000000	HALT; 000001	WAIT ;000002	RTI	Return from interrupt: PC < (SP)+; PS < (SP)+ ;000003	BPT	Breakpoint trap: -(SP) < PS; -(SP) < PC; PC < (14); PS < (16) ;000004	IOT	I/O trap: -(SP) < PS; -(SP) < PC; PC < (20); PS < (22) ;000005	RESET ;000006	RTT	Return from trap: PC < (SP)+; PS < (SP)+        DCOM BRer        DCOM BNEer        DCOM BEQer        DCOM BGEer        DCOM BLTer        DCOM BGTer        DCOM BLEer        DCOM CALLer        DCOM CALLer        DCOM CLR_COM_INC_DEC        DCOM NEG_ADC_SBC_TST        DCOM ROR_ROL_ASR_ASL        DCOM c0064_MFPI_MTPI_SXT        DCOM PANIC        DCOM PANIC;#1X
        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer        DCOM MOVer;#2X
        DCOM CMPer
        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer        DCOM CMPer;#3X
        DCOM BITer
        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer        DCOM BITer;#4X
        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer        DCOM BICer;#5X
        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer        DCOM BISer;#6x
        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer        DCOM ADDer;#7x
        DCOM MULer        DCOM MULer        DCOM DIVer        DCOM DIVer        DCOM ASHer        DCOM ASHer        DCOM ASHCer        DCOM ASHCer        DCOM XORer        DCOM XORer        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM SOBer        DCOM SOBer;#8x
        DCOM BPLer        DCOM BMIer        DCOM BHIer        DCOM BLOSer        DCOM BVCer        DCOM BVSer        DCOM BCCer ;BCC or BHIS	Branch if carry clear, or Branch if higher or same C = 0        DCOM BCSer ;BCS or BLO	Branch if carry set, or Branch if lower C = 1        DCOM EMTer;PANIC        DCOM TRAPer;PANIC        DCOM CLRB_COMB_INCB_DECB        DCOM NEGB_ADCB_SBCB_TSTB        DCOM RORB_ROLB_ASRB_ASLB        DCOM MTPS_MFPD_MTPD_MFPS        DCOM PANIC        DCOM PANIC;#9x
        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer        DCOM MOVBer;#Ax
        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer        DCOM CMPBer;#Bx
        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer        DCOM BITBer;#Cx
        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer        DCOM BICBer;#Dx
        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer        DCOM BISBer;#Ex
        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer        DCOM SUBer;#Fx
        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM PANIC        DCOM FFFFer;PANIC
	DISPLAY $-MAINCOMS,"=256"
        ORG $+256