BIN	:= atelnet.com
INSTDIR := bin/
CONSOLE := BDOS

SRCC	:= main.c term.c term_doc.c cp437toatm.c netglue.c telnet_sess.c ansi_file.c
SRCH	:= atelnet.h term_doc.h netglue.h telnet_sess.h ansi_file.h
SRCA	:= termscr.asm
XCLFILE	:= lnk.xcl

include ../iarlib/iar.mk
