BIN		:= emptyres.com
INSTDIR := bin/kapps
CONSOLE := TTY

SRCC	:= main.c app_bank.c resident.c
SRCH	:= emptyres_inc.h emptyres_plug.h app_bank.h
SRCA	:=
XCLFILE	:= lnk.xcl

include ../iarlib/iar.mk
