	EXPORT _fin
	EXPORT _fout
	EXPORT _waseof
findfile
	LD A,TRUE
	LD [findfile.res],A
	LD A,0x00
	LD [findfile.sector],A
findfile.C.
	LD HL,DOSBUF
	LD [readsectors.A.],HL
	LD A,[findfile.sector]
	LD L,A
	LD H,0
	LD [readsectors.B.],HL
	LD A,0x01
	LD [readsectors.C.],A
	CALL readsectors
	LD HL,DOSBUF
	LD [pdesc],HL
findfile.E.
	LD HL,[findfile.pfcb]
	LD DE,FCB.fn
	ADD HL,DE
	LD [findfile.pfn],HL
	LD A,0x00
	LD [findfile.i],A
findfile.G.
	LD HL,[findfile.pfn]
	LD A,[HL]
	LD [findfile.b],A
	LD HL,[findfile.pfn]
	INC HL
	LD [findfile.pfn],HL
	LD HL,[pdesc]
	LD A,[findfile.i]
	LD E,A
	LD D,0
	ADD HL,DE
	LD A,[HL]
	LD L,A
	LD A,[findfile.b]
	SUB L
	JP Z,findfile.I.
	JP findfile.wrong
findfile.I.
	LD HL,findfile.i
	INC [HL]
	LD A,[findfile.i]
	LD L,A
	LD A,[findfile.namesz]
	SUB L
	JP NZ,findfile.G.
findfile.H.
	JP findfile.found
findfile.wrong
	LD HL,[pdesc]
	LD DE,16
	ADD HL,DE
	LD [pdesc],HL
	LD HL,[pdesc]
	LD DE,DOSBUFEND
	OR A
	SBC HL,DE
	JP NZ,findfile.E.
findfile.F.
	LD HL,findfile.sector
	INC [HL]
	LD A,[findfile.sector]
	SUB 0x08
	JP NZ,findfile.C.
findfile.D.
	LD A,FALSE
	LD [findfile.res],A
findfile.found
	LD A,[findfile.res]
	RET
findlastslash
	EXPORT findlastslash
	EXPORT findlastslash.A.
	EXPORT findlastslash.slast
findlastslash.loopslash
	LD HL,[findlastslash.s]
	LD [findlastslash.slast],HL
findlastslash.loop
	LD HL,[findlastslash.s]
	LD A,[HL]
	LD [findlastslash.c],A
	LD HL,[findlastslash.s]
	INC HL
	LD [findlastslash.s],HL
	LD A,[findlastslash.c]
	SUB '\0'
	JP NZ,findlastslash.B.
	JP findlastslash.quit
findlastslash.B.
	LD A,[findlastslash.c]
	SUB '/'
	JP NZ,findlastslash.D.
	JP findlastslash.loopslash
findlastslash.D.
	JP findlastslash.loop
findlastslash.quit
	LD HL,[findlastslash.slast]
	RET
nfopen
	EXPORT nfopen
	EXPORT nfopen.A.
	EXPORT nfopen.B.
	EXPORT nfopen.pfcb
	LD HL,FCB1
	LD DE,0x0200
	OR A
	SBC HL,DE
	LD [nfopen.pfcb],HL
	LD A,0x09
	LD [nfopen.i],A
nfopen.C.
	LD HL,[nfopen.pfcb]
	LD DE,0x0200
	ADD HL,DE
	LD [nfopen.pfcb],HL
	LD HL,[nfopen.pfcb]
	LD A,[HL]
	SUB 0x00
	JP NZ,nfopen.C.
nfopen.D.
	LD HL,[nfopen.pfcb]
	LD DE,FCB.fn
	ADD HL,DE
	LD [pdesc],HL
	LD HL,nfopen.E.
	LD [memcopy.A.],HL
	LD HL,9
	LD [memcopy.B.],HL
	LD HL,[pdesc]
	LD [memcopy.C.],HL
	CALL memcopy
	LD HL,[nfopen.filename]
	LD [findlastslash.A.],HL
	CALL findlastslash
	LD [nfopen.filename],HL
nfopen.F.
	LD HL,[nfopen.filename]
	LD A,[HL]
	LD [nfopen.c],A
	LD A,[nfopen.c]
	SUB '\0'
	JP NZ,nfopen.H.
	JP nfopen.nfopenfnq
nfopen.H.
	LD HL,[nfopen.filename]
	INC HL
	LD [nfopen.filename],HL
	LD A,[nfopen.c]
	SUB '.'
	JP NZ,nfopen.J.
	JP nfopen.nfopenfndot
nfopen.J.
	LD HL,[pdesc]
	LD A,[nfopen.c]
	LD [HL],A
	LD HL,[pdesc]
	INC HL
	LD [pdesc],HL
	LD HL,nfopen.i
	DEC [HL]
	LD A,[nfopen.i]
	SUB 0x00
	JP NZ,nfopen.F.
nfopen.G.
	JP nfopen.nfopenfnq
nfopen.nfopenfndot
	LD HL,[nfopen.pfcb]
	LD DE,FCB.ext
	ADD HL,DE
	LD DE,[nfopen.filename]
	LD A,[DE]
	LD [HL],A
nfopen.nfopenfnq
	LD HL,[nfopen.pfcb]
	LD DE,FCB.block
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[nfopen.pfcb]
	LD DE,FCB.blockpad
	ADD HL,DE
	LD A,0x60
	LD [HL],A
	LD HL,[nfopen.pmode]
	LD A,[HL]
	SUB 'w'
	JP Z,nfopen.L.
	LD HL,[nfopen.pfcb]
	LD [findfile.A.],HL
	LD A,0x09
	LD [findfile.B.],A
	CALL findfile
	CPL
	OR A
	JP Z,nfopen.N.
	LD HL,0
	LD [nfopen.pfcb],HL
	JP nfopen.nfopenfail
nfopen.N.
	LD HL,[pdesc]
	LD [memcopy.A.],HL
	LD HL,11
	LD [memcopy.B.],HL
	LD HL,[nfopen.pfcb]
	LD DE,FCB.fn
	ADD HL,DE
	LD [memcopy.C.],HL
	CALL memcopy
nfopen.L.
	LD HL,[nfopen.pfcb]
	LD DE,FCB.lastlenLSB
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[nfopen.pfcb]
	LD DE,FCB.lastlenHSB
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[nfopen.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[nfopen.pfcb]
	LD DE,FCB.remain
	ADD HL,DE
	LD A,0xff
	LD [HL],A
	LD HL,[nfopen.pfcb]
	LD DE,FCB.secwritten
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[nfopen.pfcb]
	LD DE,FCB.mode
	ADD HL,DE
	LD DE,[nfopen.pmode]
	LD A,[DE]
	LD [HL],A
nfopen.nfopenfail
	LD HL,[nfopen.pfcb]
	RET
openwrite
	EXPORT openwrite
	EXPORT openwrite.A.
	LD HL,[openwrite.s]
	LD [nfopen.A.],HL
	LD HL,openwrite.B.
	LD [nfopen.B.],HL
	CALL nfopen
	RET
flushdesc
	LD HL,[flushdesc.pfcb]
	LD DE,FCB.descpos
	ADD HL,DE
	LD A,[HL]
	LD E,0x04
	LD L,A
	CALL _SHRB.
	LD H,0
	LD [flushdesc.trsec],HL
	LD HL,DOSBUF
	LD DE,[flushdesc.pfcb]
	LD BC,FCB.descpos
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD C,0x04
	LD E,A
	PUSH HL
	LD H,D
	LD L,E
	LD D,B
	LD E,C
	CALL _SHLB.
	LD H,0
	POP DE
	EX DE,HL
	ADD HL,DE
	EX DE,HL
	LD [pdesc],DE
	LD HL,DOSBUF
	LD [readsectors.A.],HL
	LD HL,[flushdesc.trsec]
	LD [readsectors.B.],HL
	LD A,0x01
	LD [readsectors.C.],A
	CALL readsectors
	LD HL,[flushdesc.pfcb]
	LD DE,FCB.fn
	ADD HL,DE
	LD [memcopy.A.],HL
	LD HL,11
	LD [memcopy.B.],HL
	LD HL,[pdesc]
	LD [memcopy.C.],HL
	CALL memcopy
	LD HL,[pdesc]
	LD DE,11
	ADD HL,DE
	LD [pdesc],HL
	LD HL,[pdesc]
	LD DE,[flushdesc.pfcb]
	LD BC,FCB.lastlenLSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[pdesc]
	INC HL
	LD [pdesc],HL
	LD HL,[pdesc]
	LD DE,[flushdesc.pfcb]
	LD BC,FCB.lastlenHSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[pdesc]
	INC HL
	LD [pdesc],HL
	LD HL,[pdesc]
	LD DE,[flushdesc.pfcb]
	LD BC,FCB.secinblk
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[pdesc]
	INC HL
	LD [pdesc],HL
	LD HL,[pdesc]
	LD DE,[flushdesc.pfcb]
	LD BC,FCB.firstsectorLSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[pdesc]
	INC HL
	LD [pdesc],HL
	LD HL,[pdesc]
	LD DE,[flushdesc.pfcb]
	LD BC,FCB.firstsectorHSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,DOSBUF
	LD [writesectors.A.],HL
	LD HL,[flushdesc.trsec]
	LD [writesectors.B.],HL
	LD A,0x01
	LD [writesectors.C.],A
	CALL writesectors
	RET
flushwritebuf
	LD HL,[flushwritebuf.pfcb]
	LD DE,0x100
	ADD HL,DE
	LD [writesectors.A.],HL
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.cursectorLSB
	ADD HL,DE
	LD A,[HL]
	LD L,A
	LD H,0
	LD DE,[flushwritebuf.pfcb]
	LD BC,FCB.cursectorHSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD E,A
	LD D,0
	LD BC,8
	PUSH HL
	LD H,D
	LD L,E
	LD D,B
	LD E,C
	CALL _SHL.
	POP DE
	EX DE,HL
	ADD HL,DE
	EX DE,HL
	LD [writesectors.B.],DE
	LD A,0x01
	LD [writesectors.C.],A
	CALL writesectors
	LD [flushwritebuf.cursector],HL
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.cursectorLSB
	ADD HL,DE
	LD DE,[flushwritebuf.cursector]
	LD [HL],E
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.cursectorHSB
	ADD HL,DE
	LD DE,[flushwritebuf.cursector]
	LD BC,8
	PUSH HL
	LD H,D
	LD L,E
	LD D,B
	LD E,C
	CALL _SHR.
	POP DE
	LD A,L
	LD [DE],A
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.secwritten
	ADD HL,DE
	INC [HL]
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.secwritten
	ADD HL,DE
	LD A,[HL]
	LD DE,[flushwritebuf.pfcb]
	LD BC,FCB.secinblk
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD L,A
	LD A,[DE]
	SUB L
	JP NZ,flushwritebuf.B.
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.secwritten
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[flushwritebuf.pfcb]
	LD [flushdesc.A.],HL
	CALL flushdesc
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.block
	ADD HL,DE
	INC [HL]
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.lastlenLSB
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[flushwritebuf.pfcb]
	LD DE,FCB.lastlenHSB
	ADD HL,DE
	LD A,0x00
	LD [HL],A
flushwritebuf.B.
	RET
flush_
	LD HL,[flush_.pfcb]
	LD DE,FCB.secwritten
	ADD HL,DE
	LD A,[HL]
	SUB 0x00
	JP NZ,flush_.B.
	LD HL,[flush_.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	LD A,0x10
	LD [HL],A
	LD HL,DOSBUF
	LD [readsectors.A.],HL
	LD HL,0x0008
	LD [readsectors.B.],HL
	LD A,0x01
	LD [readsectors.C.],A
	CALL readsectors
	LD HL,DOSBUFfreesectorsHSB
	LD A,[HL]
	LD L,A
	LD H,0
	LD DE,8
	CALL _SHL.
	LD DE,DOSBUFfreesectorsLSB
	LD A,[DE]
	LD E,A
	LD D,0
	ADD HL,DE
	LD DE,16
	OR A
	SBC HL,DE
	LD [flush_.freesectors],HL
	LD HL,DOSBUFfreesectorsLSB
	LD DE,[flush_.freesectors]
	LD [HL],E
	LD HL,DOSBUFfreesectorsHSB
	LD DE,[flush_.freesectors]
	LD BC,8
	PUSH HL
	LD H,D
	LD L,E
	LD D,B
	LD E,C
	CALL _SHR.
	POP DE
	LD A,L
	LD [DE],A
	LD HL,[flush_.pfcb]
	LD DE,FCB.descpos
	ADD HL,DE
	LD DE,DOSBUFfiles
	LD A,[DE]
	LD [HL],A
	LD HL,DOSBUFfiles
	LD DE,[flush_.pfcb]
	LD BC,FCB.descpos
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	ADD A,0x01
	LD [HL],A
	LD HL,DOSBUFfreesectorLSB
	LD A,[HL]
	LD [flush_.firstsectorLSB],A
	LD HL,DOSBUFfreesectorHSB
	LD A,[HL]
	LD [flush_.firstsectorHSB],A
	LD HL,[flush_.pfcb]
	LD DE,FCB.firstsectorLSB
	ADD HL,DE
	LD A,[flush_.firstsectorLSB]
	LD [HL],A
	LD HL,[flush_.pfcb]
	LD DE,FCB.firstsectorHSB
	ADD HL,DE
	LD A,[flush_.firstsectorHSB]
	LD [HL],A
	LD HL,[flush_.pfcb]
	LD DE,FCB.cursectorLSB
	ADD HL,DE
	LD A,[flush_.firstsectorLSB]
	LD [HL],A
	LD HL,[flush_.pfcb]
	LD DE,FCB.cursectorHSB
	ADD HL,DE
	LD A,[flush_.firstsectorHSB]
	LD [HL],A
	LD HL,DOSBUFfreesectorHSB
	LD A,[flush_.firstsectorHSB]
	ADD A,0x01
	LD [HL],A
	LD HL,DOSBUF
	LD [writesectors.A.],HL
	LD HL,0x0008
	LD [writesectors.B.],HL
	LD A,0x01
	LD [writesectors.C.],A
	CALL writesectors
flush_.B.
	LD HL,[flush_.pfcb]
	LD [flushwritebuf.A.],HL
	CALL flushwritebuf
	RET
fread1sec
	LD HL,[fread1sec.pfcb]
	LD DE,0x100
	ADD HL,DE
	LD [readsectors.A.],HL
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.cursectorLSB
	ADD HL,DE
	LD A,[HL]
	LD L,A
	LD H,0
	LD DE,[fread1sec.pfcb]
	LD BC,FCB.cursectorHSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD E,A
	LD D,0
	LD BC,8
	PUSH HL
	LD H,D
	LD L,E
	LD D,B
	LD E,C
	CALL _SHL.
	POP DE
	EX DE,HL
	ADD HL,DE
	EX DE,HL
	LD [readsectors.B.],DE
	LD A,0x01
	LD [readsectors.C.],A
	CALL readsectors
	LD [fread1sec.cursector],HL
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.cursectorLSB
	ADD HL,DE
	LD DE,[fread1sec.cursector]
	LD [HL],E
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.cursectorHSB
	ADD HL,DE
	LD DE,[fread1sec.cursector]
	LD BC,8
	PUSH HL
	LD H,D
	LD L,E
	LD D,B
	LD E,C
	CALL _SHR.
	POP DE
	LD A,L
	LD [DE],A
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.remain
	ADD HL,DE
	LD A,0x00
	LD [HL],A
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	DEC [HL]
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	LD A,[HL]
	SUB 0x00
	JP NZ,fread1sec.B.
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.lastlenLSB
	ADD HL,DE
	LD A,[HL]
	SUB 0x01
	LD [fread1sec.eod],A
	LD HL,[fread1sec.pfcb]
	LD DE,0x0100
	ADD HL,DE
	LD A,[fread1sec.eod]
	LD E,A
	LD D,0
	ADD HL,DE
	LD [memcopyback.A.],HL
	LD A,[fread1sec.eod]
	LD L,A
	LD H,0
	LD DE,1
	ADD HL,DE
	LD [memcopyback.B.],HL
	LD HL,[fread1sec.pfcb]
	LD DE,0x01ff
	ADD HL,DE
	LD [memcopyback.C.],HL
	CALL memcopyback
	LD HL,[fread1sec.pfcb]
	LD DE,FCB.remain
	ADD HL,DE
	LD A,[fread1sec.eod]
	CPL
	LD [HL],A
fread1sec.B.
	RET
fread1blkq
	LD A,FALSE
	LD [fread1blkq.res],A
	LD HL,[fread1blkq.pdesc]
	LD [memcopy.A.],HL
	LD HL,11
	LD [memcopy.B.],HL
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.fn
	ADD HL,DE
	LD [memcopy.C.],HL
	CALL memcopy
	LD HL,[fread1blkq.pdesc]
	LD DE,11
	ADD HL,DE
	LD [fread1blkq.pdesc],HL
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.lastlenLSB
	ADD HL,DE
	LD DE,[fread1blkq.pdesc]
	LD A,[DE]
	LD [HL],A
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.lastlenHSB
	ADD HL,DE
	LD DE,[fread1blkq.pdesc]
	LD BC,1
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[fread1blkq.pdesc]
	LD DE,2
	ADD HL,DE
	LD [fread1blkq.pdesc],HL
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	LD DE,[fread1blkq.pdesc]
	LD A,[DE]
	LD [HL],A
	LD HL,[fread1blkq.pdesc]
	INC HL
	LD [fread1blkq.pdesc],HL
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.firstsectorLSB
	ADD HL,DE
	LD DE,[fread1blkq.pdesc]
	LD A,[DE]
	LD [HL],A
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.firstsectorHSB
	ADD HL,DE
	LD DE,[fread1blkq.pdesc]
	LD BC,1
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.cursectorLSB
	ADD HL,DE
	LD DE,[fread1blkq.pfcb]
	LD BC,FCB.firstsectorLSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.cursectorHSB
	ADD HL,DE
	LD DE,[fread1blkq.pfcb]
	LD BC,FCB.firstsectorHSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD [HL],A
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	LD DE,[fread1blkq.pfcb]
	LD BC,FCB.lastlenLSB
	EX DE,HL
	ADD HL,BC
	EX DE,HL
	LD A,[DE]
	LD E,A
	LD D,0
	LD BC,[fread1blkq.pfcb]
	LD IX,FCB.lastlenHSB
	LD A,C
	ADD A,LX
	LD C,A
	LD A,B
	ADC A,HX
	LD B,A
	LD A,[BC]
	LD C,A
	LD B,0
	LD IX,8
	PUSH HL
	PUSH DE
	LD H,B
	LD L,C
	LD D,HX
	LD E,LX
	CALL _SHL.
	POP DE
	EX DE,HL
	ADD HL,DE
	EX DE,HL
	LD HL,0x00ff
	EX DE,HL
	ADD HL,DE
	EX DE,HL
	LD HL,8
	PUSH DE
	LD D,H
	LD E,L
	POP HL
	CALL _SHR.
	POP DE
	LD A,L
	LD [DE],A
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	LD A,[HL]
	SUB 0x00
	JP Z,fread1blkq.C.
	LD HL,[fread1blkq.pfcb]
	LD DE,FCB.block
	ADD HL,DE
	INC [HL]
	LD A,TRUE
	LD [fread1blkq.res],A
fread1blkq.C.
	LD A,[fread1blkq.res]
	RET
readnewbuf
	LD A,FALSE
	LD [readnewbuf.res],A
	LD HL,[readnewbuf.pfcb]
	LD DE,FCB.secinblk
	ADD HL,DE
	LD A,[HL]
	SUB 0x00
	JP NZ,readnewbuf.B.
	LD HL,[readnewbuf.pfcb]
	LD [findfile.A.],HL
	LD A,0x0a
	LD [findfile.B.],A
	CALL findfile
	CPL
	OR A
	JP Z,readnewbuf.D.
	JP readnewbuf.quit
readnewbuf.D.
	LD HL,[readnewbuf.pfcb]
	LD [fread1blkq.A.],HL
	LD HL,[readnewbuf.pdesc]
	LD [fread1blkq.B.],HL
	CALL fread1blkq
	CPL
	OR A
	JP Z,readnewbuf.F.
	JP readnewbuf.quit
readnewbuf.F.
readnewbuf.B.
	LD HL,[readnewbuf.pfcb]
	LD [fread1sec.A.],HL
	CALL fread1sec
	LD A,TRUE
	LD [readnewbuf.res],A
readnewbuf.quit
	LD A,[readnewbuf.res]
	RET
fputs
	EXPORT fputs
	EXPORT fputs.A.
	EXPORT fputs.B.
	EXPORT fputs.c
fputs.loop
	LD HL,[fputs.s]
	LD A,[HL]
	LD [fputs.c],A
	LD A,[fputs.c]
	SUB '\0'
	JP NZ,fputs.C.
	JP fputs.quit
fputs.C.
	LD HL,fputs.c
	LD [fwrite.A.],HL
	LD HL,1
	LD [fwrite.B.],HL
	LD HL,1
	LD [fwrite.C.],HL
	LD HL,[fputs.file]
	LD [fwrite.D.],HL
	CALL fwrite
	LD HL,[fputs.s]
	INC HL
	LD [fputs.s],HL
	JP fputs.loop
fputs.quit
	LD HL,1
	RET
fclose
	EXPORT fclose
	EXPORT fclose.A.
	EXPORT fclose.pfcb
	LD HL,[fclose.file]
	LD [fclose.pfcb],HL
	LD HL,[fclose.pfcb]
	LD DE,FCB.mode
	ADD HL,DE
	LD A,[HL]
	LD [fclose.mode],A
	LD HL,[fclose.pfcb]
	LD DE,FCB.mode
	ADD HL,DE
	LD A,'\0'
	LD [HL],A
	LD A,[fclose.mode]
	SUB 'w'
	JP NZ,fclose.B.
	LD HL,[fclose.pfcb]
	LD [flush_.A.],HL
	CALL flush_
	LD HL,[fclose.pfcb]
	LD DE,FCB.secwritten
	ADD HL,DE
	LD A,[HL]
	SUB 0x00
	JP Z,fclose.D.
	LD HL,[fclose.pfcb]
	LD [flushdesc.A.],HL
	CALL flushdesc
fclose.D.
fclose.B.
	LD HL,1
	RET
