#название запускаемого файла
BIN		:= yad.com

#поддиректория инсталляции в release
INSTDIR := bin

#тип вводавывода TTY или BDOS
CONSOLE := BDOS

#файлы .с
SRCC	:= main.c
#файлы .h
SRCH	:=
#файлы .asm
SRCA	:= yadplay.asm
#линковочный файл-скрипт. можно не указывать, тогда будет использоватся стандартный
XCLFILE	:= lnk.xcl


include ../../dmapps/iarlib/iar.mk
