
tnvcmds
        db key_redraw
        db key_enter
        db key_backspace
        db key_left
        db key_right
        db key_down
        db key_up
        db key_esc
        db key_tab
	db ss1;'!'
	db ss2;'@'
	db ss3;'#'
	db ss4;'$'
        db '0'
        db '1'
        db '2'
        db '3'
        db '4'
        db '5'
        db '6'
        db '7'
        db '8'
        db '9'
        db ' '
        db key_pgup
        db key_pgdown
        db ss5;'%'
        db '*'
        db key_home
        db key_end
nnvcmds=$-tnvcmds       
        dw editcmd_End
        dw editcmd_Home
        dw editcmd_invfiles
        dw editcmd_ss5
        dw editcmd_pageDown
        dw editcmd_pageUp
	dw editcmd_space
        dw editcmd_9
        dw editcmd_8
        dw editcmd_7
        dw editcmd_6
        dw editcmd_5
        dw editcmd_4
        dw editcmd_3
        dw editcmd_2
        dw editcmd_1
	dw editcmd_0
        dw editcmd_ss4
        dw editcmd_ss3
        dw editcmd_ss2
        dw editcmd_ss1
        dw editcmd_tab
        dw editcmd_quit
        dw editcmd_up
        dw editcmd_down
        dw editcmd_right
        dw editcmd_left
        dw editcmd_backspace
        dw editcmd_enter
        dw editcmd_reprintall_keepcursor
