; Pull common IAR helpers into nco.com so every ovl link
; keeps the same 0100-7FFF layout (mbovl root-hash / check-addrs).
; When a bank starts calling new libc/OS symbols, EXTERN them here too.
	MODULE force_helpers
	PUBLIC force_helpers

	EXTERN ?L_ADDASG_L03
	EXTERN ?L_SUBASG_L03
	EXTERN ?L_DEC_L03
	EXTERN ?L_S_SWITCH_L06
	EXTERN ?S_S_SWITCH_L06
	EXTERN ?S_V_SWITCH_L06
	EXTERN ?S_MUL_L02
	EXTERN ?L_MUL_L03
	EXTERN ?UC_DIV_L01
	EXTERN ?C_MUL_L01
	EXTERN ?US_RSH_L02
	EXTERN ?US_DIV_L02
	EXTERN ?US_DIVASG_IY_L12
	EXTERN ?US_MOD_L02
	EXTERN ?SS_MOD_L02
	EXTERN ?UL_RSH_L03
	EXTERN ?UL_MOD_L03
	EXTERN ?UL_DIVASG_L03
	EXTERN ?UL_DIV_L03
	EXTERN ?C_S_SWITCH_L06
	EXTERN ?C_V_SWITCH_L06
	EXTERN ?CLZ80L_4_06_L00
	EXTERN ?STRCPY_L11
	EXTERN ?STRLEN_L11
	EXTERN ?MEMSET_L11
	EXTERN ?STRCMP_L11
	EXTERN ?STRCAT_L11
	EXTERN ?STRCHR_L11
	EXTERN OS_GETMAINPAGES
	EXTERN OS_DELPAGE
	EXTERN OS_GETAPPMAINPAGES
	EXTERN OS_NEWAPP
	EXTERN OS_RUNAPP
	EXTERN OS_WAITPID
	EXTERN OS_DROPAPP
	EXTERN strncat
	EXTERN m_run_restore_ui
	EXTERN g_bankPg
	EXTERN residentPg
	EXTERN g_run_saved_cwd
	EXTERN g_run_cmdline
	EXTERN g_run_inner
	EXTERN g_run_name
	EXTERN g_ini_viewer
	EXTERN g_ini_editor
	EXTERN g_ini_cmd_flag
	EXTERN m_run_action_view
	EXTERN m_run_action_edit
	EXTERN m_run_action_selected
	EXTERN m_cmd_clear
	EXTERN m_cmd_begin
	EXTERN m_cmd_handle_key
	EXTERN m_cmd_fill_bottom_snap
	EXTERN m_cmd_execute
	EXTERN g_cmd_active
	EXTERN g_cmd_len
	EXTERN g_cmd_cursor
	EXTERN g_cmd_line
	EXTERN g_nvext_size
	EXTERN g_ncext_off
	EXTERN g_ncext_size
	EXTERN g_run_handler
	EXTERN g_nvext_io
	EXTERN g_ui_nv_ext
	EXTERN left_panel
	EXTERN right_panel
	EXTERN OS_DELETE
	EXTERN OS_RENAME
	EXTERN OS_SETFILETIME
	EXTERN OS_CHDIR
	EXTERN OS_OPENDIR
	EXTERN OS_READDIR
	EXTERN OS_SETPGC000
	EXTERN OS_SETSYSDRV
	EXTERN m_panels_remap_bank_window
	EXTERN g_snap_left
	EXTERN g_snap_right
	EXTERN g_ui_folder_pfx
	EXTERN m_panel_chdir_only
	EXTERN m_redraw_panels_full
	EXTERN OS_GETFILESIZE
	EXTERN OS_GETFILETIME
	EXTERN OS_SEEKHANDLE
	EXTERN OS_OPENHANDLE
	EXTERN OS_READHANDLE
	EXTERN OS_CLOSEHANDLE
	EXTERN OS_CREATEHANDLE
	EXTERN OS_WRITEHANDLE
	EXTERN OS_GETPATH
	EXTERN OS_SETXY
	EXTERN OS_SETCOLOR
	EXTERN OS_CLS
	EXTERN OS_GETTIME
	EXTERN OS_CHDRV
	EXTERN OS_GETKEY
	EXTERN OS_GETFILINFO
	EXTERN YIELD
	EXTERN putchar
	EXTERN strncpy
	EXTERN panel_files_scroll_up
	EXTERN panel_files_scroll_down

	RSEG CODE
force_helpers:
	ld	hl,?L_ADDASG_L03
	ld	hl,?L_SUBASG_L03
	ld	hl,?L_DEC_L03
	ld	hl,?L_S_SWITCH_L06
	ld	hl,?S_S_SWITCH_L06
	ld	hl,?S_V_SWITCH_L06
	ld	hl,?S_MUL_L02
	ld	hl,?L_MUL_L03
	ld	hl,?UC_DIV_L01
	ld	hl,?C_MUL_L01
	ld	hl,?US_RSH_L02
	ld	hl,?US_DIV_L02
	ld	hl,?US_DIVASG_IY_L12
	ld	hl,?US_MOD_L02
	ld	hl,?SS_MOD_L02
	ld	hl,?UL_RSH_L03
	ld	hl,?UL_MOD_L03
	ld	hl,?UL_DIVASG_L03
	ld	hl,?UL_DIV_L03
	ld	hl,?C_S_SWITCH_L06
	ld	hl,?C_V_SWITCH_L06
	ld	hl,?CLZ80L_4_06_L00
	ld	hl,?STRCPY_L11
	ld	hl,?STRLEN_L11
	ld	hl,?MEMSET_L11
	ld	hl,?STRCMP_L11
	ld	hl,?STRCAT_L11
	ld	hl,?STRCHR_L11
	ld	hl,OS_GETMAINPAGES
	ld	hl,OS_DELPAGE
	ld	hl,OS_GETAPPMAINPAGES
	ld	hl,OS_NEWAPP
	ld	hl,OS_RUNAPP
	ld	hl,OS_WAITPID
	ld	hl,OS_DROPAPP
	ld	hl,strncat
	ld	hl,m_run_restore_ui
	ld	hl,g_bankPg
	ld	hl,residentPg
	ld	hl,g_run_saved_cwd
	ld	hl,g_run_cmdline
	ld	hl,g_run_inner
	ld	hl,g_run_name
	ld	hl,g_ini_viewer
	ld	hl,g_ini_editor
	ld	hl,g_ini_cmd_flag
	ld	hl,m_run_action_view
	ld	hl,m_run_action_edit
	ld	hl,m_run_action_selected
	ld	hl,m_cmd_clear
	ld	hl,m_cmd_begin
	ld	hl,m_cmd_handle_key
	ld	hl,m_cmd_fill_bottom_snap
	ld	hl,m_cmd_execute
	ld	hl,g_cmd_active
	ld	hl,g_cmd_len
	ld	hl,g_cmd_cursor
	ld	hl,g_cmd_line
	ld	hl,g_nvext_size
	ld	hl,g_ncext_off
	ld	hl,g_ncext_size
	ld	hl,g_run_handler
	ld	hl,g_nvext_io
	ld	hl,g_ui_nv_ext
	ld	hl,left_panel
	ld	hl,right_panel
	ld	hl,OS_DELETE
	ld	hl,OS_RENAME
	ld	hl,OS_SETFILETIME
	ld	hl,OS_CHDIR
	ld	hl,OS_OPENDIR
	ld	hl,OS_READDIR
	ld	hl,OS_SETPGC000
	ld	hl,OS_SETSYSDRV
	ld	hl,m_panels_remap_bank_window
	ld	hl,g_snap_left
	ld	hl,g_snap_right
	ld	hl,g_ui_folder_pfx
	ld	hl,m_panel_chdir_only
	ld	hl,m_redraw_panels_full
	ld	hl,OS_GETFILESIZE
	ld	hl,OS_GETFILETIME
	ld	hl,OS_SEEKHANDLE
	ld	hl,OS_OPENHANDLE
	ld	hl,OS_READHANDLE
	ld	hl,OS_CLOSEHANDLE
	ld	hl,OS_CREATEHANDLE
	ld	hl,OS_WRITEHANDLE
	ld	hl,OS_GETPATH
	ld	hl,OS_SETXY
	ld	hl,OS_SETCOLOR
	ld	hl,OS_CLS
	ld	hl,OS_GETTIME
	ld	hl,OS_CHDRV
	ld	hl,OS_GETKEY
	ld	hl,OS_GETFILINFO
	ld	hl,YIELD
	ld	hl,putchar
	ld	hl,strncpy
	ld	hl,panel_files_scroll_up
	ld	hl,panel_files_scroll_down
	ret

	END
