#ifndef NC_PANEL_H
#define NC_PANEL_H

#define BANK_WINDOW_ADDRESS 0xC000u
#define BANK_PAGE_SIZE 16384u
#define FILINFO_RECORD_SIZE 86u
#define FILES_PER_PAGE 180u
#define PANEL_PAGE_FILES_BYTES (FILES_PER_PAGE * FILINFO_RECORD_SIZE)
#define PANEL_META_IDX_SIZE 2u
#define PANEL_FILE_PAGES 3u
#define PANEL_META_PAGE 3u
#define MAX_FILES_PER_PANEL (FILES_PER_PAGE * PANEL_FILE_PAGES)
#define PANEL_SORT_NOTICE_FILES 50u
#define PANEL_SORT_KEY_LEN 4u
#define PANEL_META_OFF_IDX 0u
#define PANEL_META_OFF_KIND (PANEL_META_OFF_IDX + MAX_FILES_PER_PANEL * PANEL_META_IDX_SIZE)
#define PANEL_META_OFF_NAME4 (PANEL_META_OFF_KIND + MAX_FILES_PER_PANEL)
#define PANEL_META_OFF_EXT4 (PANEL_META_OFF_NAME4 + MAX_FILES_PER_PANEL * PANEL_SORT_KEY_LEN)
#define PANEL_META_OFF_LFN4 (PANEL_META_OFF_EXT4 + MAX_FILES_PER_PANEL * PANEL_SORT_KEY_LEN)
#define PANEL_META_OFF_LFNEXT4 (PANEL_META_OFF_LFN4 + MAX_FILES_PER_PANEL * PANEL_SORT_KEY_LEN)
#define PANEL_META_OFF_SIZE (PANEL_META_OFF_LFNEXT4 + MAX_FILES_PER_PANEL * PANEL_SORT_KEY_LEN)
#define PANEL_META_OFF_DATE (PANEL_META_OFF_SIZE + MAX_FILES_PER_PANEL * 4u)
#define PANEL_META_OFF_TIME (PANEL_META_OFF_DATE + MAX_FILES_PER_PANEL * 2u)
#define PANEL_META_OFF_MARK (PANEL_META_OFF_TIME + MAX_FILES_PER_PANEL * 2u)
#define PANEL_META_MARK_BYTES MAX_FILES_PER_PANEL
#define PANEL_META_USED_BYTES (PANEL_META_OFF_MARK + PANEL_META_MARK_BYTES)
#define NC_NVEXT_OFF PANEL_META_USED_BYTES
#define NC_NVEXT_SPARE (BANK_PAGE_SIZE - PANEL_META_USED_BYTES)
#define NC_NVEXT_MAX 1024u
#define NC_EXT_HANDLER_MAX 96u
#define PANEL_KIND_FILE 0u
#define PANEL_KIND_DIR 1u
#define PANEL_KIND_DOTDOT 2u
#define PANEL_ROW_WIDTH 38u
#define PANEL_VIEW_ROWS 18u
#define PANEL_READ_STAGE 12u

#define NC_KEY_HOME 28u
#define NC_KEY_END 30u
#define NC_KEY_FOCUS 31u
#define NC_KEY_UP 250u
#define NC_KEY_DOWN 249u
#define NC_KEY_PGUP 248u
#define NC_KEY_PGDN 251u
#define NC_KEY_TAB 9u
#define NC_KEY_ENTER 13u
#define NC_KEY_CSENTER 253u
#define NC_KEY_DEL_FWD 252u
#define NC_KEY_SS0 95u
#define NC_KEY_SS1 33u
#define NC_KEY_SS2 64u /* '@' Symbol Shift+2 ? match nc */
#define NC_KEY_SS3 35u
#define NC_KEY_SS4 36u
#define NC_KEY_SS5 37u
#define NC_KEY_SS6 38u
#define NC_KEY_SS7 39u
#define NC_KEY_SS8 40u
#define NC_KEY_SS9 41u
#define NC_KEY_F10 0xb0u
#define NC_KEY_F1 0xb1u
#define NC_KEY_F2 0xb2u
#define NC_KEY_F3 0xb3u
#define NC_KEY_F4 0xb4u
#define NC_KEY_F5 0xb5u
#define NC_KEY_F6 0xb6u
#define NC_KEY_F7 0xb7u
#define NC_KEY_F8 0xb8u
#define NC_KEY_F9 0xb9u
#define NC_KEY_MARK_INS 29u
#define NC_KEY_MARK_STAR 42u
#define NC_KEY_MOVE 94u

#endif
