PLAYERSTART = 0x4000

	macro PLAYERHEADER
	dw playerinit
	dw playerdeinit
	dw musicload
	dw musicunload
	dw musicplay
	dw isfilesupported
	dw playernamestr
	dw 0
	dw 0
	endm

PLAYERINITPROCADDR      = PLAYERSTART+0x00
PLAYERDEINITPROCADDR    = PLAYERSTART+0x02
MUSICLOADPROCADDR       = PLAYERSTART+0x04
MUSICUNLOADPROCADDR     = PLAYERSTART+0x06
MUSICPLAYPROCADDR       = PLAYERSTART+0x08
ISFILESUPPORTEDPROCADDR = PLAYERSTART+0x0a
PLAYERNAMESTRADDR       = PLAYERSTART+0x0c
MUSICTITLEADDR          = PLAYERSTART+0x0e
MUSICPROGRESSADDR       = PLAYERSTART+0x10
