NAME		= player.com
OBJECTS		=
SOURCES		= player.asm
RESOURCES	=
DOCS		=
BIN_INSTALLDIR	:= ${INSTALLDIR}/bin
RES_INSTALLDIR	:= ${INSTALLDIR}/bin
DOC_INSTALLDIR	:= ${INSTALLDIR}/doc

include ../_sdk/common.mk
