;Какие проигрыватели загружать
UseNGS=1
UseMWM=1
UsePT3=1
UseVGM=1
UseMoonMod=1

;MoonModDefaultPanning используется когда .mod не контролирует панорамирование
;(не использует 8xy или E8x команды). 0 значит канал полностью слева, F канал
;полностью справа. 0FF0 соотв. конфигурации Амиги, 8888 моно звуку.
MoonModDefaultPanning=5AA5

;Плеер сам в зависимости от скорости системы определит требуюмую задержку для
;реализации программного UART для внешнего MIDI, но если MIDI в итоге работает
;неустойчиво, то можно попробовать настроить задержку вручную прописав значение
;отличное от нуля. Для nowait 3.5Мгц значение должно быть ~?, для nowait 7Мгц ~16,
;для 14Мгц ZX Evolution ~23.
MidiUartDelayOverride=0
