BIN		:= tdesk.com
INSTDIR := bin
CONSOLE := BDOS
SRCC	:= main.c wm.c wm_ctrl.c wm_form.c wm_button.c wm_label.c wm_edit.c bank.c vtxt.c ui_mouse.c
SRCH	:= wm.h wm_ctrl.h wm_form.h wm_button.h wm_label.h wm_edit.h bank.h vtxt.h cp866toatm.inc ui_mouse.h forms_demo.inc winApi.txt
SRCA	:= vtxt_blit.asm
XCLFILE	:= lnk.xcl
include ../iarlib/iar.mk
