NAME = mkfs_fat.exe
OBJS = mkfs.fat device_info common charconv mingw-termios my_getline

CFLAGS = -D_POSIX_C_SOURCE=200809L -O2 -Wall -g

CC = i686-w64-mingw32-gcc


.PHONY: all
all: $(NAME)

include $(OBJS:%=%.d)

%.d: %.c
	$(CC) -MM $(CFLAGS) $< | sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' > $@

$(NAME): $(OBJS:%=%.o)
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm $(NAME) $(OBJS:%=%.o) $(OBJS:%=%.d)

%.o: %.c Makefile.w32
	$(CC) $(CFLAGS) -c -o $@ $<
