;GS memory layout
GSPROGSTART = 0x4000
GSSTACKADDR = 0x5d00
GSINTERRUPTTABLEENTRYADDR = 0x5eff

;GS commands
CMDRESTART = 0
CMDGETFREEBUFFERSPACE = 1
CMDGETCHIPID = 2
CMDRESTARTSTREAM = 3
CMDVOLUMEUP = 4
CMDVOLUMEDOWN = 5
