#название запускаемого файла
BIN		:=zxartrad.com

#поддиректория инсталляции в release
INSTDIR := bin/Radio

#тип вводавывода TTY или BDOS
CONSOLE := TTY_NE

#файлы .с
SRCC	:= main.c
#файлы .h
SRCH	:=
#файлы .asm
SRCA	:=
#линковочный файл-скрипт. можно не указывать, тогда будет использоватся стандартный
XCLFILE	:= lnk.xcl


include ../iarlib/iar.mk
