BIN		:= time2.com

INSTDIR := bin

CONSOLE := TTY

SRCC	:= main.c
SRCH	:= ../iarlib/espnet.h ../common/espnet/protocol.h ../common/espnet.c ../common/espnet-net.c ../common/esp-com.c ../common/network.c ../common/ini.c
SRCA	:=
XCLFILE	:= lnk.xcl

include ../iarlib/iar.mk
