BIN     := svnesp.com
INSTDIR := bin
CONSOLE := TTY

SRCC    := main.c
SRCH    := crc32.h ../common/esp-com.c ../common/network.c ../common/espnet.c ../common/espnet-net.c ../iarlib/espnet.h ../common/ini.c
SRCA    := crc32.asm
XCLFILE := lnk.xcl

include ../iarlib/iar.mk
