        include "gfxinc.asm"
        dw body0
        dw body1
        dw body2
        dw body3
        dw body4
        dw body5
        dw body6
        dw body7
        dw body8
        dw body9
        dw body10
        dw body11
        dw body12
        dw body13
        dw body14
        dw body15
        dw body16
        include "WBODY.ast"
        include "gfxinc2.asm"
	savebin "br/WBODY.bin",begin,end-begin
