        include "gfxinc.asm"
        dw fire0
        dw fire1
        dw fire2
        dw fire3
        dw fire4
        dw fire5
        dw fire6
        dw fire7
        dw fire8
        dw magic0
        dw magic1
        dw magic2
        dw tornado0
        dw tornado1
        dw tornado2
        dw foam0
        dw foam1
        dw foam2
        dw arrow0
        dw arrow1
        dw arrow2
        dw arrow3
        dw spell0
        dw spell1
        dw spell2
        dw spell3
        dw projectile0
        dw projectile1
        dw projectile2
        dw projectile3
        dw projectile4
        dw projectile5
        dw projectile6
        dw projectile7
        dw fireball
        dw icefall
        dw magicbubble
        dw fireballs0
        dw fireballs1
        dw fireballs2
        dw explosion0
        dw explosion1
        dw explosion2
        include "WBULLET.ast"
        include "gfxinc2.asm"
	savebin "br/WBULLET.bin",begin,end-begin
