        include "gfxinc.asm"
        dw stenogryz0
        dw stenogryz0step
        dw stenogryz1
        dw stenogryz1step
        dw stenogryz2
        dw stenogryz2step
        dw stenogryz3
        dw stenogryz3step
        dw stenogryz4
        dw stenogryz4step
        dw stenogryz5
        dw stenogryz5step
        dw stenogryz6
        dw stenogryz6step
        dw stenogryz7
        dw stenogryz7step
        dw stenogryz0hit
        dw stenogryz1hit
        dw stenogryz2hit
        dw stenogryz3hit
        dw stenogryz4hit
        dw stenogryz5hit
        dw stenogryz6hit
        dw stenogryz7hit
        include "WCREAT2c.ast"
        include "gfxinc2.asm"
	savebin "br/WCREAT2c.bin",begin,end-begin
