        include "gfxinc.asm"
        dw stenogryz0
        dw stenogryz0step
        dw stenogryz1
        dw stenogryz1step
        dw stenogryz2
        dw stenogryz2step
        dw stenogryz3
        dw stenogryz3step
        dw stenogryz4
        dw stenogryz4step
        dw stenogryz5
        dw stenogryz5step
        dw stenogryz6
        dw stenogryz6step
        dw stenogryz7
        dw stenogryz7step
        dw stenogryz0hit
        dw stenogryz1hit
        dw stenogryz2hit
        dw stenogryz3hit
        dw stenogryz4hit
        dw stenogryz5hit
        dw stenogryz6hit
        dw stenogryz7hit

        dw body0
        dw body1
        dw body2
        dw body3
        dw body4
        dw body5
        dw body6
        dw body7
        dw body8
        dw body9
        dw body10
        dw body11
        dw body12
        dw body13
        dw body14
        dw body15
        dw body16
        dw body16 ;труп чужой катапульты?
        include "WCREAT2c.ast"
        include "WBODY.ast"
        include "gfxinc2.asm"
	savebin "br/WCREAT2c.bin",begin,end-begin
