        include "gfxinc.asm"
        dw kost0
        dw kost0step
        dw kost1
        dw kost1step
        dw kost2
        dw kost2step
        dw kost3
        dw kost3step
        dw kost4
        dw kost4step
        dw kost5
        dw kost5step
        dw kost6
        dw kost6step
        dw kost7
        dw kost7step
        dw kost0hit
        dw kost1hit
        dw kost2hit
        dw kost3hit
        dw kost4hit
        dw kost5hit
        dw kost6hit
        dw kost7hit
        include "WCREAT2.ast"
        ds 0xe800-$
        include "demobar.ast"
        include "gfxinc2.asm"
	savebin "br/WCREAT2.bin",begin,end-begin
