        include "gfxinc.asm"
        dw demon0
        dw demon0step
        dw demon1
        dw demon1step
        dw demon2
        dw demon2step
        dw demon3
        dw demon3step
        dw demon4
        dw demon4step
        dw demon5
        dw demon5step
        dw demon6
        dw demon6step
        dw demon7
        dw demon7step
        dw demon0hit
        dw demon1hit
        dw demon2hit
        dw demon3hit
        dw demon4hit
        dw demon5hit
        dw demon6hit
        dw demon7hit
        include "WCREAT2b.ast"
        include "gfxinc2.asm"
	savebin "br/WCREAT2b.bin",begin,end-begin
