        include "gfxinc.asm"
        dw spider0
        dw spider0step
        dw spider1
        dw spider1step
        dw spider2
        dw spider2step
        dw spider3
        dw spider3step
        dw spider4
        dw spider4step
        dw spider5
        dw spider5step
        dw spider6
        dw spider6step
        dw spider7
        dw spider7step
        dw spider0hit
        dw spider1hit
        dw spider2hit
        dw spider3hit
        dw spider4hit
        dw spider5hit
        dw spider6hit
        dw spider7hit
        dw skeleton0
        dw skeleton0step
        dw skeleton1
        dw skeleton1step
        dw skeleton2
        dw skeleton2step
        dw skeleton3
        dw skeleton3step
        dw skeleton4
        dw skeleton4step
        dw skeleton5
        dw skeleton5step
        dw skeleton6
        dw skeleton6step
        dw skeleton7
        dw skeleton7step
        dw skeleton0hit
        dw skeleton1hit
        dw skeleton2hit
        dw skeleton3hit
        dw skeleton4hit
        dw skeleton5hit
        dw skeleton6hit
        dw skeleton7hit
        include "WCREAT1.ast"
        include "gfxinc2.asm"
	savebin "br/WCREAT1.bin",begin,end-begin
