        include "gfxinc.asm"
        dw humpope0
        dw humpope0step
        dw humpope1
        dw humpope1step
        dw humpope2
        dw humpope2step
        dw humpope3
        dw humpope3step
        dw humpope4
        dw humpope4step
        dw humpope5
        dw humpope5step
        dw humpope6
        dw humpope6step
        dw humpope7
        dw humpope7step
        dw humpope0hit
        dw humpope1hit
        dw humpope2hit
        dw humpope3hit
        dw humpope4hit
        dw humpope5hit
        dw humpope6hit
        dw humpope7hit
        dw hummage0
        dw hummage0step
        dw hummage1
        dw hummage1step
        dw hummage2
        dw hummage2step
        dw hummage3
        dw hummage3step
        dw hummage4
        dw hummage4step
        dw hummage5
        dw hummage5step
        dw hummage6
        dw hummage6step
        dw hummage7
        dw hummage7step
        dw hummage0hit
        dw hummage1hit
        dw hummage2hit
        dw hummage3hit
        dw hummage4hit
        dw hummage5hit
        dw hummage6hit
        dw hummage7hit
        include "WHUM1c.ast"
        include "gfxinc2.asm"
	savebin "br/WHUM1c.bin",begin,end-begin
