        include "gfxinc.asm"
        dw humarc0
        dw humarc0step
        dw humarc1
        dw humarc1step
        dw humarc2
        dw humarc2step
        dw humarc3
        dw humarc3step
        dw humarc4
        dw humarc4step
        dw humarc5
        dw humarc5step
        dw humarc6
        dw humarc6step
        dw humarc7
        dw humarc7step
        dw humblade0
        dw humblade0step
        dw humblade1
        dw humblade1step
        dw humblade2
        dw humblade2step
        dw humblade3
        dw humblade3step
        dw humblade4
        dw humblade4step
        dw humblade5
        dw humblade5step
        dw humblade6
        dw humblade6step
        dw humblade7
        dw humblade7step
        dw humblade0hit
        dw humblade1hit
        dw humblade2hit
        dw humblade3hit
        dw humblade4hit
        dw humblade5hit
        dw humblade6hit
        dw humblade7hit
        include "WHUM1b.ast"
        include "gfxinc2.asm"
;	savebin "br/WHUM1b.bin",begin,end-begin
