        include "gfxinc.asm"
        dw humcat0
        dw humcat0step
        dw humcat1
        dw humcat1step
        dw humcat2
        dw humcat2step
        dw humcat3
        dw humcat3step
        dw humcat4
        dw humcat4step
        dw humcat5
        dw humcat5step
        dw humcat6
        dw humcat6step
        dw humcat7
        dw humcat7step
        dw humcat0hit
        dw humcat1hit
        dw humcat2hit
        dw humcat3hit
        dw humcat4hit
        dw humcat5hit
        dw humcat6hit
        dw humcat7hit
        include "WHUMCAT.ast"
        include "gfxinc2.asm"
;	savebin "br/WHUMCAT.bin",begin,end-begin
