        include "gfxinc.asm"
        dw human0
        dw human0step
        dw human1
        dw human1step
        dw human2
        dw human2step
        dw human3
        dw human3step
        dw human4
        dw human4step
        dw human5
        dw human5step
        dw human6
        dw human6step
        dw human7
        dw human7step
        dw human0hit
        dw human1hit
        dw human2hit
        dw human3hit
        dw human4hit
        dw human5hit
        dw human6hit
        dw human7hit
        dw humanwood0
        dw humanwood0step
        dw humanwood1
        dw humanwood1step
        dw humanwood2
        dw humanwood2step
        dw humanwood3
        dw humanwood3step
        dw humanwood4
        dw humanwood4step
        dw humanwood5
        dw humanwood5step
        dw humanwood6
        dw humanwood6step
        dw humanwood7
        dw humanwood7step
        dw humangold0
        dw humangold0step
        dw humangold1
        dw humangold1step
        dw humangold2
        dw humangold2step
        dw humangold3
        dw humangold3step
        dw humangold4
        dw humangold4step
        dw humangold5
        dw humangold5step
        dw humangold6
        dw humangold6step
        dw humangold7
        dw humangold7step
        include "WHUM1.ast"
        include "gfxinc2.asm"
;	savebin "br/WHUM1.bin",begin,end-begin
