        include "gfxinc.asm"
        dw orccat0
        dw orccat0step
        dw orccat1
        dw orccat1step
        dw orccat2
        dw orccat2step
        dw orccat3
        dw orccat3step
        dw orccat4
        dw orccat4step
        dw orccat5
        dw orccat5step
        dw orccat6
        dw orccat6step
        dw orccat7
        dw orccat7step
        dw orccat0hit
        dw orccat1hit
        dw orccat2hit
        dw orccat3hit
        dw orccat4hit
        dw orccat5hit
        dw orccat6hit
        dw orccat7hit
        include "WORCCAT.ast"
        include "gfxinc2.asm"
;	savebin "br/WORCCAT.bin",begin,end-begin
