        include "gfxinc.asm"
        dw orchor0
        dw orchor0step
        dw orchor1
        dw orchor1step
        dw orchor2
        dw orchor2step
        dw orchor3
        dw orchor3step
        dw orchor4
        dw orchor4step
        dw orchor5
        dw orchor5step
        dw orchor6
        dw orchor6step
        dw orchor7
        dw orchor7step
        dw orchor0hit
        dw orchor1hit
        dw orchor2hit
        dw orchor3hit
        dw orchor4hit
        dw orchor5hit
        dw orchor6hit
        dw orchor7hit
        include "WORCHOR.ast"
        include "gfxinc2.asm"
	savebin "br/WORCHOR.bin",begin,end-begin
