        include "gfxinc.asm"
        dw orcarc0
        dw orcarc0step
        dw orcarc1
        dw orcarc1step
        dw orcarc2
        dw orcarc2step
        dw orcarc3
        dw orcarc3step
        dw orcarc4
        dw orcarc4step
        dw orcarc5
        dw orcarc5step
        dw orcarc6
        dw orcarc6step
        dw orcarc7
        dw orcarc7step
        dw orcblade0
        dw orcblade0step
        dw orcblade1
        dw orcblade1step
        dw orcblade2
        dw orcblade2step
        dw orcblade3
        dw orcblade3step
        dw orcblade4
        dw orcblade4step
        dw orcblade5
        dw orcblade5step
        dw orcblade6
        dw orcblade6step
        dw orcblade7
        dw orcblade7step
        dw orcblade0hit
        dw orcblade1hit
        dw orcblade2hit
        dw orcblade3hit
        dw orcblade4hit
        dw orcblade5hit
        dw orcblade6hit
        dw orcblade7hit
        include "WORC1b.ast"
        include "gfxinc2.asm"
	savebin "br/WORC1b.bin",begin,end-begin
