        include "gfxinc.asm"
        dw orc0
        dw orc0step
        dw orc1
        dw orc1step
        dw orc2
        dw orc2step
        dw orc3
        dw orc3step
        dw orc4
        dw orc4step
        dw orc5
        dw orc5step
        dw orc6
        dw orc6step
        dw orc7
        dw orc7step
        dw orc0hit
        dw orc1hit
        dw orc2hit
        dw orc3hit
        dw orc4hit
        dw orc5hit
        dw orc6hit
        dw orc7hit
        dw orcwood0
        dw orcwood0step
        dw orcwood1
        dw orcwood1step
        dw orcwood2
        dw orcwood2step
        dw orcwood3
        dw orcwood3step
        dw orcwood4
        dw orcwood4step
        dw orcwood5
        dw orcwood5step
        dw orcwood6
        dw orcwood6step
        dw orcwood7
        dw orcwood7step
        dw orcgold0
        dw orcgold0step
        dw orcgold1
        dw orcgold1step
        dw orcgold2
        dw orcgold2step
        dw orcgold3
        dw orcgold3step
        dw orcgold4
        dw orcgold4step
        dw orcgold5
        dw orcgold5step
        dw orcgold6
        dw orcgold6step
        dw orcgold7
        dw orcgold7step
        include "WORC1.ast"
        include "gfxinc2.asm"
;	savebin "br/WORC1.bin",begin,end-begin
