        include "gfxinc.asm"
        dw orcpope0
        dw orcpope0step
        dw orcpope1
        dw orcpope1step
        dw orcpope2
        dw orcpope2step
        dw orcpope3
        dw orcpope3step
        dw orcpope4
        dw orcpope4step
        dw orcpope5
        dw orcpope5step
        dw orcpope6
        dw orcpope6step
        dw orcpope7
        dw orcpope7step
        dw orcpope0hit
        dw orcpope1hit
        dw orcpope2hit
        dw orcpope3hit
        dw orcpope4hit
        dw orcpope5hit
        dw orcpope6hit
        dw orcpope7hit
        dw orcmage0
        dw orcmage0step
        dw orcmage1
        dw orcmage1step
        dw orcmage2
        dw orcmage2step
        dw orcmage3
        dw orcmage3step
        dw orcmage4
        dw orcmage4step
        dw orcmage5
        dw orcmage5step
        dw orcmage6
        dw orcmage6step
        dw orcmage7
        dw orcmage7step
        dw orcmage0hit
        dw orcmage1hit
        dw orcmage2hit
        dw orcmage3hit
        dw orcmage4hit
        dw orcmage5hit
        dw orcmage6hit
        dw orcmage7hit
        include "WORC1c.ast"
        include "gfxinc2.asm"
	savebin "br/WORC1c.bin",begin,end-begin
