BIN		:= ngsplay.com

INSTDIR := bin

CONSOLE := BDOS

SRCC	:= main.c ui_mouse.c ngs_host.c ngs_mp3.c ngs_mod.c ngsdrv_bin.c ngsldr_bin.c neopg2_bin.c gscode_bin.c app_bank.c ngs_resident.c
SRCH	:= ngsplay.h app_bank.h ngs_plug.h ui_mouse.h
SRCA	:= gs_io.asm
XCLFILE	:= lnk.xcl

include ../iarlib/iar.mk
