BIN		:= ngsplay.com

INSTDIR := bin

CONSOLE := BDOS

SRCC	:= main.c ngs_host.c ngsdrv_bin.c ngsldr_bin.c neopg2_bin.c
SRCH	:= ngsplay.h
SRCA	:= gs_io.asm
XCLFILE	:= lnk.xcl

include ../iarlib/iar.mk
