#ifndef NGSPLAY_H
#define NGSPLAY_H

/* GS blob symbols (generated by gs/bin2c.py) */
extern const unsigned char ngsdrv_bin[];
extern const unsigned int ngsdrv_bin_len;
extern const unsigned char ngsldr_bin[];
extern const unsigned int ngsldr_bin_len;
extern const unsigned char neopg2_bin[];
extern const unsigned int neopg2_bin_len;

/* Return 0 on success, non-zero on error/timeout */
unsigned char ngs_detect(void);
unsigned char ngs_bootstrap(void);
unsigned char ngs_upload(const unsigned char *src, unsigned int len, unsigned int gs_addr);
unsigned char ngs_jump(unsigned int gs_addr);
unsigned char ngs_set_page3(unsigned char page);
unsigned char ngs_peek_nt(void);

unsigned char ngs_start_load(unsigned char slot, const unsigned char *header256);
unsigned char ngs_get_next_block(unsigned char *type, unsigned int *ofs256, unsigned int *len256);
unsigned char ngs_save_block(const unsigned char *data, unsigned char pages256);
unsigned char ngs_init_sample(unsigned char module, unsigned char smp);
unsigned char ngs_start_play(unsigned char module, unsigned char order);
unsigned char ngs_stop_play(void);
unsigned char ngs_cont_play(void);
unsigned char ngs_status_play(void);

/* Load S3M from NedoOS file into NeoGS slot 0. Returns 0 ok. */
unsigned char ngs_load_s3m(unsigned char *path, unsigned char *title_out);

#endif
