# tgvplay ? AloneVid FMV player (C + asm hot path)
BIN		:= tgvplay.com

INSTDIR := bin

CONSOLE := BDOS

SRCC	:= main.c fmv.c
SRCH	:= tgvplay.h
SRCA	:= tgv_hot.asm
XCLFILE	:= lnk.xcl

include ../iarlib/iar.mk
