/* Auto-generated by gen_nc_mem.py from IAR link map. Do not edit. */
#ifndef NC_MEM_H
#define NC_MEM_H

#define NC_MAIN_BASE           0x0100u
#define NC_MAIN_LIMIT          0xBFFFu
#define NC_MAIN_SIZE           0xBF00u
#define NC_MAIN_USED_END       0xAF30u /* CSTACK top */
#define NC_MAIN_FREE           0x10CFu
#define NC_MAIN_CODE_BYTES     55559u
#define NC_MAIN_DATA_BYTES     5184u

#define NC_RES_BASE            0xC000u
#define NC_RES_LIMIT           0xFFFFu
#define NC_RES_SIZE            0x4000u
#define NC_RES_CODE_END        0xFF23u
#define NC_RES_CODE_USED       0x3F24u
#define NC_RES_CODE_FREE       0x00DCu

#endif
